---
permalink: online-help-96-97/concept_how_you_update_cluster_nondisruptively.html 
sidebar: sidebar 
keywords: update, cluster, nondisruptively, plan, perpare, perform, system, manager, online, help 
summary: System Manager를 사용하여 클러스터를 특정 ONTAP 버전으로 중단 없이 업데이트할 수 있습니다. 무중단 업데이트를 위해서는 ONTAP 이미지를 선택하고 클러스터가 업데이트 준비가 되었는지 확인한 다음 업데이트를 수행해야 합니다. 
---
= 클러스터를 무중단으로 업데이트합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager를 사용하여 클러스터를 특정 ONTAP 버전으로 중단 없이 업데이트할 수 있습니다. 무중단 업데이트를 위해서는 ONTAP 이미지를 선택하고 클러스터가 업데이트 준비가 되었는지 확인한 다음 업데이트를 수행해야 합니다.

무중단 업데이트 중에 클러스터는 온라인 상태를 유지하며 계속해서 데이터를 제공합니다.



== 업데이트 계획 및 준비

클러스터 업데이트를 계획하고 준비하는 과정에서 NetApp Support 사이트에서 클러스터를 업데이트할 ONTAP 이미지의 버전을 받아야 합니다. 그런 다음 소프트웨어 이미지를 선택하고 검증을 수행해야 합니다. 사전 업데이트 검증에서는 클러스터가 선택한 버전으로 업데이트할 준비가 되었는지 확인합니다.

유효성 검사가 오류 및 경고와 함께 완료되면 필요한 수정 조치를 수행하여 오류 및 경고를 해결한 다음 클러스터 구성 요소가 업데이트를 위한 준비가 되었는지 확인해야 합니다. 예를 들어, 업데이트 전 검증이 진행되는 동안 오프라인 애그리게이트가 클러스터에 포함되어 있다는 경고가 표시되면 애그리게이트 페이지로 이동한 다음 모든 오프라인 애그리게이트의 상태를 온라인으로 변경해야 합니다.



== 업데이트를 수행하는 중입니다

클러스터를 업데이트하면 전체 클러스터가 업데이트되거나 고가용성(HA) 쌍의 노드가 업데이트됩니다. 업데이트 과정에서 업데이트 전 검증이 다시 실행되어 클러스터가 업데이트 준비 상태인지 확인합니다.

클러스터에 있는 노드 수에 따라 롤링 업데이트 또는 일괄 업데이트가 수행됩니다.

* * 업데이트 중 *
+
노드 중 하나가 오프라인 상태가 되고 파트너 노드가 해당 노드의 스토리지를 이어주는 동안 업데이트됩니다.

+
두 개 이상의 노드로 구성된 클러스터에 대해 롤링 업데이트가 수행됩니다. 8개 미만의 노드가 있는 클러스터에는 이 업데이트 방법밖에 없습니다.

* * 일괄 업데이트 *
+
클러스터는 두 개의 배치로 분할되며, 각 배치에는 여러 HA 쌍이 포함됩니다.

+
8개 이상의 노드로 구성된 클러스터에 대해 일괄 업데이트가 수행됩니다. 이러한 클러스터에서는 일괄 업데이트나 롤링 업데이트를 수행할 수 있습니다. 8개 이상의 노드가 있는 클러스터의 기본 업데이트 방법입니다.



* 관련 정보 *

xref:task_updating_cluster_nondisruptively.adoc[클러스터를 중단 없이 업데이트]
