---
permalink: online-help-96-97/concept_roles_delete.html 
sidebar: sidebar 
keywords: system, manager, create, manage, role, online, help, svm, edit 
summary: System Manager를 사용하여 역할을 만들고 관리할 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 역할을 만들고 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하여 역할을 만들고 관리할 수 있습니다.



== 역할을 추가합니다

System Manager를 사용하여 액세스 제어 역할을 추가하고 해당 역할의 사용자가 액세스할 수 있는 명령 또는 명령 디렉토리를 지정할 수 있습니다. 명령 또는 명령 디렉터리에 대한 역할의 액세스 수준을 제어할 수 있으며 명령 또는 명령 디렉터리에 적용되는 쿼리를 지정할 수도 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. SVM 사용자 세부 정보 * 창에서 * 역할 * 을 클릭합니다.
. 추가 * 를 클릭합니다.
. 역할 추가 * 대화 상자에서 역할 이름을 지정한 다음 역할 특성을 추가합니다.
. 추가 * 를 클릭합니다.




== 역할을 편집합니다

System Manager를 사용하면 명령 또는 명령 디렉터리에 대한 액세스 제어 roleroleto 를 수정하고 지정된 명령 집합에만 대한 사용자 액세스를 제한할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. SVM 사용자 세부 정보 * 창에서 * 역할 * 을 클릭합니다.
. 수정할 역할을 선택한 다음 * 편집 * 을 클릭합니다.
. 역할 속성을 수정한 다음 * 수정 * 을 클릭합니다.




== 역할 창

역할 창을 사용하여 사용자 계정과 연결된 역할을 관리할 수 있습니다.



=== 명령 버튼

* * 추가 *
+
역할 추가 대화 상자를 엽니다. 이 대화 상자에서 액세스 제어 역할을 만들고 해당 역할의 사용자가 액세스할 수 있는 명령 또는 명령 디렉터리를 지정할 수 있습니다.

* * 편집 *
+
역할 속성을 추가하거나 수정할 수 있는 역할 편집 대화 상자를 엽니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 역할 목록

역할 목록에는 사용자에게 할당할 수 있는 역할 목록이 제공됩니다.



=== 역할 특성 영역

세부 정보 영역에는 선택한 역할이 액세스할 수 있는 명령 또는 명령 디렉터리, 액세스 수준 및 명령 또는 명령 디렉터리에 적용되는 쿼리와 같은 역할 특성이 표시됩니다.

* 관련 정보 *

https://docs.netapp.com/us-en/ontap/authentication/index.html["관리자 인증 및 RBAC"^]
