---
permalink: online-help-96-97/concept_thin_provisioning_for_greater_efficiencies_using_flexvol_volumes.html 
sidebar: sidebar 
keywords: thin, provisioning, greater, efficiencies, flexvol, volume, online, help, lun 
summary: 씬 프로비저닝을 사용하면 주어진 애그리게이트에서 볼륨 및 LUN을 생성할 때 실제로 해당 볼륨에 공간을 할당하지 않습니다. 데이터가 볼륨 또는 LUN에 기록될 때 공간이 할당됩니다. 
---
= 씬 프로비저닝: FlexVol 볼륨을 사용하여 효율성 향상
:icons: font
:imagesdir: ../media/


[role="lead"]
씬 프로비저닝을 사용하면 주어진 애그리게이트에서 볼륨 및 LUN을 생성할 때 실제로 해당 볼륨에 공간을 할당하지 않습니다. 데이터가 볼륨 또는 LUN에 기록될 때 공간이 할당됩니다.

사용되지 않는 애그리게이트 공간은 다른 볼륨 및 LUN에서 사용할 수 있습니다. 필요에 따라 용량을 할당하고 공간을 재확보하여 씬 프로비저닝을 통해 스토리지 사용률을 높이고 스토리지 비용을 줄일 수 있습니다.

FlexVol 볼륨은 포함된 애그리게이트를 다른 FlexVol 볼륨과 공유할 수 있습니다. 따라서 단일 Aggregate는 이 Aggregate에 포함된 FlexVol 볼륨에서 사용하는 모든 스토리지의 공유 소스입니다. 유연한 볼륨은 더 이상 볼륨이 상주하는 디스크의 제한 사항에 구속되지 않습니다. FlexVol 볼륨은 디스크 크기가 아니라 저장할 데이터의 양을 기준으로 크기를 조정할 수 있습니다. 이러한 유연성 덕분에 스토리지 시스템의 성능과 용량 활용률을 극대화할 수 있습니다. FlexVol 볼륨은 시스템에서 사용 가능한 모든 물리적 스토리지에 액세스할 수 있으므로 스토리지 활용도가 향상됩니다.

500GB 볼륨은 실제 데이터가 100GB로만 할당되고, 나머지 400GB 용량에는 저장된 데이터가 없습니다. 이 사용되지 않는 용량은 응용 프로그램이 나중에 모든 400GB 용량을 필요로 하지 않더라도 비즈니스 응용 프로그램에 할당됩니다. 할당되었지만 사용되지 않은 400GB의 초과 용량이 일시적으로 낭비됩니다.

씬 프로비저닝을 사용하면 스토리지 관리자가 비즈니스 애플리케이션에 500GB를 프로비저닝하지만 데이터에 100GB만 사용합니다. 차이점은 씬 프로비저닝을 사용할 경우 사용되지 않는 400GB를 다른 애플리케이션에서 계속 사용할 수 있다는 점입니다. 이러한 접근 방식을 통해 애플리케이션이 투명하게 증가하고 물리적 스토리지가 애플리케이션이 필요할 때만 완전히 할당됩니다. 나머지 스토리지는 필요에 따라 사용할 수 있는 여유 풀에 남아 있습니다.
