---
permalink: online-help-96-97/concept_requirements_best_practices_for_using_ssd_storage_pools.html 
sidebar: sidebar 
keywords: requirements, best, practices, ssd, storage, flash, pool, aggregate, online, help 
summary: 일부 기술은 SSD 스토리지 풀을 사용하는 Flash Pool 애그리게이트와 결합할 수 없습니다. 
---
= SSD 스토리지 풀 사용에 대한 요구사항 및 모범 사례
:icons: font
:imagesdir: ../media/


[role="lead"]
일부 기술은 SSD 스토리지 풀을 사용하는 Flash Pool 애그리게이트와 결합할 수 없습니다.

캐시 스토리지에 SSD 스토리지 풀을 사용하는 Flash Pool 애그리게이트에는 다음 기술을 사용할 수 없습니다.

* MetroCluster
* SyncMirror 기능
+
미러링된 애그리게이트는 스토리지 풀을 사용하는 Flash Pool 애그리게이트와 공존할 수 있지만 Flash Pool 애그리게이트는 미러링할 수 없습니다.

* 물리적 SSD
+
Flash Pool 애그리게이트는 SSD 스토리지 풀 또는 물리적 SSD를 사용할 수 있지만 둘 다 사용할 수는 없습니다.



SSD 스토리지 풀은 다음 규칙을 준수해야 합니다.

* SSD 스토리지 풀에는 SSD만 포함될 수 있으며 HDD는 SSD 스토리지 풀에 추가할 수 없습니다.
* SSD 스토리지 풀에 있는 모든 SSD는 동일한 HA(고가용성) 쌍이 소유해야 합니다.
* 스토리지 풀에서 루트 데이터 파티셔닝으로 분할된 SSD는 사용할 수 없습니다.


단일 스토리지 풀에서 다른 RAID 유형의 두 개의 캐시로 스토리지를 제공하고 스토리지 풀의 크기를 RAID4의 최대 RAID 그룹 크기 이상으로 확장하는 경우 RAID4 할당 유닛의 추가 파티션은 사용되지 않습니다. 따라서 캐시 RAID 유형을 스토리지 풀에 대해 동일하게 유지하는 것이 가장 좋습니다.

스토리지 풀에서 할당된 캐시 RAID 그룹의 RAID 유형은 변경할 수 없습니다. 첫 번째 할당 유닛을 추가하기 전에 캐시에 대한 RAID 유형을 설정하며 나중에 RAID 유형을 변경할 수 없습니다.

스토리지 풀을 생성하거나 기존 스토리지 풀에 SSD를 추가할 때 동일한 크기의 SSD를 사용해야 합니다. 장애가 발생하고 올바른 크기의 스페어 SSD가 존재하지 않는 경우, ONTAP는 더 큰 SSD를 사용하여 장애가 발생한 SSD를 대체할 수 있습니다. 하지만 이보다 큰 SSD의 크기는 스토리지 풀의 다른 SSD 크기와 일치하도록 적당한 크기이므로 SSD 용량이 손실될 수 있습니다.

스토리지 풀에는 하나의 예비 SSD만 사용할 수 있습니다. 스토리지 풀에서 HA 쌍의 두 노드가 소유한 Flash Pool 애그리게이트에 할당 유닛을 제공하는 경우, 두 노드 중 하나의 스페어 SSD를 소유할 수 있습니다. 하지만 스토리지 풀에서 HA 쌍의 노드 중 하나가 소유하는 Flash Pool 애그리게이트에만 할당 유닛을 제공하는 경우, SSD 스페어는 동일한 노드에서 소유해야 합니다.
