---
permalink: online-help-96-97/concept_minimum_number_hot_spares_you_should_have.html 
sidebar: sidebar 
keywords: minimum, number, hot, spares, disks, requirement, technical, support, online, help 
summary: '여유 공간이 부족하면 사용 가능한 스페어가 없는 상태에서 디스크 장애가 발생할 위험이 증가하며 이로 인해 RAID 그룹이 저하됩니다. 컨트롤러 중단 시 기술 지원을 위해 중요한 정보(핵심 파일)를 제공하려면 예비 디스크도 필요합니다.' 
---
= 디스크에 필요한 최소 핫 스페어 수입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
여유 공간이 부족하면 사용 가능한 스페어가 없는 상태에서 디스크 장애가 발생할 위험이 증가하며 이로 인해 RAID 그룹이 저하됩니다. 컨트롤러 중단 시 기술 지원에 중요한 정보(A_CORE 파일_)를 제공하려면 예비 디스크도 필요합니다.

mSATA 디스크 또는 멀티 디스크 캐리어의 디스크는 정상 상태 작동 중에 4개의 핫 스페어를 가지고 있어야 하며 mSATA 핫 스페어 수가 2개 이하로 떨어지도록 하면 안 됩니다.

SSD로 구성된 RAID 그룹의 경우 스페어 디스크가 하나 이상 있어야 합니다.

다른 모든 ONTAP 디스크 유형의 경우 스토리지 시스템에 설치된 각 디스크 종류에 맞는 핫 스페어 또는 적절한 핫 스페어를 하나 이상 사용할 수 있어야 합니다. 그러나 모든 디스크에 사용 가능한 핫 스페어 두 개를 가지고 있으면 디스크 장애로부터 최상의 보호 기능을 제공할 수 있습니다. 사용 가능한 핫 스페어가 2개 이상 있으면 다음과 같은 이점이 있습니다.

* 데이터 디스크에 대해 2개 이상의 핫 스페어가 있는 경우, 필요한 경우 ONTAP를 통해 해당 디스크를 유지보수 센터에 넣을 수 있습니다.
+
ONTAP는 유지보수 센터를 사용하여 의심되는 디스크를 테스트하고 문제를 나타내는 디스크를 오프라인으로 만듭니다.

* 두 개의 핫 스페어를 사용한다는 것은 디스크에 오류가 발생한 경우에도 첫 번째 오류 디스크를 교체하기 전에 다른 디스크에 오류가 발생한 경우에도 스페어 디스크를 사용할 수 있음을 의미합니다.


단일 스페어 디스크는 여러 RAID 그룹의 핫 스페어로 사용될 수 있습니다. 그러나 이러한 RAID 그룹의 디스크에 장애가 발생하면 나중에 디스크 장애가 발생하거나 스페어 디스크를 교체할 때까지 코어 파일에 사용할 수 있는 스페어 디스크가 없습니다. 따라서 둘 이상의 스페어를 두는 것이 좋습니다.
