---
permalink: online-help-96-97/concept_quota_limits.html 
sidebar: sidebar 
keywords: quota, limit, disk, space, files 
summary: 디스크 공간 제한을 적용하거나 각 할당량 유형의 파일 수를 제한할 수 있습니다. 할당량에 대한 제한을 지정하지 않으면 적용되지 않습니다. 
---
= 할당량 제한입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
디스크 공간 제한을 적용하거나 각 할당량 유형의 파일 수를 제한할 수 있습니다. 할당량에 대한 제한을 지정하지 않으면 적용되지 않습니다.

할당량은 소프트 또는 하드일 수 있습니다. 소프트 할당량을 사용하면 Data ONTAP에서 지정된 제한을 초과할 때 알림을 보내고, 하드 할당량을 사용하면 지정된 제한을 초과할 때 쓰기 작업이 성공하지 못합니다.

하드 할당량은 시스템 리소스에 엄격한 제한을 부과하며, 제한을 초과하는 작업은 모두 실패합니다. 다음 설정은 하드 할당량을 생성합니다.

* Disk Limit 매개 변수입니다
* 파일 제한 매개 변수


소프트 할당량은 리소스 사용량이 특정 수준에 도달해도 데이터 액세스 작업에는 영향을 주지 않으므로 할당량이 초과되기 전에 적절한 조치를 취할 수 있도록 경고 메시지를 보냅니다. 다음 설정은 소프트 할당량을 생성합니다.

* Disk Limit 매개 변수의 임계값입니다
* 소프트 디스크 제한 매개 변수입니다
* 소프트 파일 제한 매개 변수


임계값 및 소프트 디스크 할당량을 통해 관리자는 할당량에 대한 알림을 두 개 이상 받을 수 있습니다. 일반적으로 관리자는 디스크 한계 임계값을 디스크 한계보다 약간 작은 값으로 설정하여 쓰기 시작 전에 임계값이 "최종 경고"를 제공할 수 있도록 합니다.

* * 디스크 공간 하드 제한값 *
+
하드 할당량에 적용되는 디스크 공간 제한입니다.

* * 디스크 공간 소프트 제한값 *
+
소프트 할당량에 적용되는 디스크 공간 제한입니다.

* * 임계값 제한 *
+
임계값 할당량에 적용되는 디스크 공간 제한입니다.

* * 파일 하드 제한값 *
+
하드 할당량에 있는 최대 파일 수입니다.

* * 파일 소프트 제한값 *
+
소프트 할당량에 있는 최대 파일 수입니다.


