---
permalink: online-help-96-97/concept_considerations_for_when_to_use_ssd_storage_pools.html 
sidebar: sidebar 
keywords: considerations, ssd, storage, pool, restrictions, online, help 
summary: SSD 스토리지 풀은 많은 이점을 제공하지만 SSD 스토리지 풀 또는 전용 SSD를 사용할지 결정할 때 유의해야 할 몇 가지 제한 사항이 있습니다. 
---
= SSD 스토리지 풀을 사용할 때의 고려 사항
:icons: font
:imagesdir: ../media/


[role="lead"]
SSD 스토리지 풀은 많은 이점을 제공하지만 SSD 스토리지 풀 또는 전용 SSD를 사용할지 결정할 때 유의해야 할 몇 가지 제한 사항이 있습니다.

SSD 스토리지 풀은 캐시를 두 개 이상의 Flash Pool 애그리게이트에 제공하는 경우에만 적합합니다. SSD 스토리지 풀은 다음과 같은 이점을 제공합니다.

* Flash Pool 애그리게이트에 사용되는 SSD의 스토리지 활용률을 높입니다
+
SSD 스토리지 풀은 두 개 이상의 Flash Pool 애그리게이트 간에 패리티 SSD를 공유할 수 있도록 지원하여 패리티에 필요한 SSD의 전체 비율을 줄입니다.

* HA 파트너 간에 스페어 공유 가능
+
스토리지 풀은 HA 쌍이 효과적으로 소유하기 때문에 HA 파트너 중 하나에서 소유하는 하나의 스페어는 필요한 경우 전체 SSD 스토리지 풀을 위한 스페어로 사용할 수 있습니다.

* SSD 성능을 더욱 효과적으로 활용
+
SSD에서 제공하는 고성능을 활용하면 HA 2노드의 두 컨트롤러에 대한 액세스를 지원할 수 있습니다.



이러한 이점은 다음과 같은 항목이 포함된 SSD 스토리지 풀 사용 비용에 대해 가중치를 두어야 합니다.

* 장애 격리 감소
+
단일 SSD가 손실되면 해당 파티션 중 하나가 포함된 모든 RAID 그룹에 영향을 미칩니다. 이 경우 영향을 받는 SSD를 포함하는 SSD 스토리지 풀에서 할당된 캐시가 있는 모든 Flash Pool 애그리게이트에 1개 이상의 RAID 그룹이 재구성 중입니다.

* 성능 격리 감소
+
Flash Pool 캐시의 크기가 올바르게 조정되지 않은 경우, Flash Pool 애그리게이트 간에 공유 중인 캐시의 경합이 발생할 수 있습니다. 이러한 위험은 적절한 캐시 사이징 및 QoS 제어를 통해 완화할 수 있습니다.

* 관리 유연성 감소
+
스토리지 풀에 스토리지를 추가하면 해당 스토리지 풀에서 하나 이상의 할당 유닛이 포함된 All Flash Pool 캐시의 크기가 늘어나며, 추가 용량이 어떻게 배포되는지 확인할 수 없습니다.


