---
permalink: online-help-96-97/concept_benefits_storage_efficiency.html 
sidebar: sidebar 
keywords: benefit, storage, efficiency, flexcone, flexvol, snapshot, copy, deduplication, data, compression, snapmirror, online, help, classic 
summary: 스토리지 효율성을 통해 최소한의 비용으로 최대 용량의 데이터를 저장하고 공간 소비를 줄이면서 급속한 데이터 증가를 수용할 수 있습니다. RAID-DP, FlexVol, Snapshot 복사본, 중복제거, 데이터 압축, 데이터 압축, SnapMirror 및 FlexClone을 사용하여 스토리지 사용률을 높이고 스토리지 비용을 줄입니다. 이러한 기술을 함께 사용하면 성능을 높일 수 있습니다. 
---
= 스토리지 효율성의 이점
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 효율성을 통해 최소한의 비용으로 최대 용량의 데이터를 저장하고 공간 소비를 줄이면서 급속한 데이터 증가를 수용할 수 있습니다. RAID-DP, FlexVol, Snapshot 복사본, 중복제거, 데이터 압축, 데이터 압축, SnapMirror 및 FlexClone을 사용하여 스토리지 사용률을 높이고 스토리지 비용을 줄입니다. 이러한 기술을 함께 사용하면 성능을 높일 수 있습니다.

* RAID-DP 기술로 완화할 수 있는 SATA(Serial Advanced Technology Attachment) 드라이브와 같은 고밀도 디스크 드라이브는 향상된 효율성과 읽기 성능을 제공합니다.
* RAID-DP는 이중 패리티 RAID6 구현이며 이중 디스크 드라이브 장애를 방지합니다.
* 씬 프로비저닝을 사용하면 할당되지 않은 공통 스토리지 공간을 필요에 따라 다른 애플리케이션에 쉽게 제공할 수 있습니다.
+
FlexVol 기술을 기반으로 합니다.

* 스냅샷 복사본은 최소 스토리지 공간을 사용하는 데이터 볼륨의 읽기 전용 시점 뷰입니다.
+
순서대로 생성된 2개의 스냅샷 복사본은 두 복사본 간의 시간 간격 동안 추가되거나 변경된 블록마다 다릅니다. 이 블록 증분 동작은 관련 스토리지 용량 사용을 제한합니다.

* 중복 제거는 FlexVol 볼륨 내에서 중복 데이터 블록을 제거하여 스토리지 공간을 절약합니다.
* 데이터 압축은 더 적은 공간에 더 많은 데이터를 저장하고 볼륨 SnapMirror 전송 중에 데이터를 복제하는 데 필요한 시간과 대역폭을 줄여 줍니다.
+
스토리지 시스템의 요구 사항과 구성을 기준으로 압축 유형(인라인 또는 백그라운드)을 선택해야 합니다. 인라인 압축은 데이터를 압축하고 압축한 다음 볼륨에 데이터를 쓸 수 있는지 확인합니다. 백그라운드 압축은 파일이 압축 가능한지 여부와 관계없이 모든 파일에 대해 실행되며, 모든 데이터가 볼륨에 기록된 후에 실행됩니다.

* SnapMirror 기술은 로컬 영역, 광역 및 파이버 채널 네트워크를 통해 데이터를 복제할 수 있는 유연한 솔루션입니다.
+
IT는 엔터프라이즈 데이터 보호 전략을 구현하는 데 중요한 구성 요소 역할을 할 수 있습니다. 하나 이상의 스토리지 시스템에 데이터를 복제하여 운영 사이트 장애 시 다운타임 비용을 최소화할 수 있습니다. SnapMirror 기술을 사용하여 여러 데이터 센터의 디스크에 데이터 백업을 중앙 집중화할 수도 있습니다.

* FlexClone 기술은 데이터 볼륨, 파일 및 LUN을 즉각적인 가상 복사본으로 복사합니다.
+
FlexClone 볼륨, 파일 또는 LUN은 FlexVol 볼륨 또는 다른 FlexClone 볼륨, 파일 또는 LUN의 쓰기 가능한 시점 이미지입니다. 이 기술을 사용하면 공간을 효율적으로 사용할 수 있으며 상위 항목과 클론 간에 변경된 데이터만 저장할 수 있습니다.

* 유니파이드 아키텍처는 멀티 프로토콜 지원을 통합하여 단일 플랫폼에서 파일 기반 스토리지와 블록 기반 스토리지를 모두 지원합니다.
+
FlexArray 가상화를 사용하면 전체 스토리지 인프라를 하나의 인터페이스에서 가상화할 수 있으며 이러한 모든 효율성을 NetApp이 아닌 시스템에 적용할 수 있습니다.


