---
permalink: online-help-96-97/concept_what_nvme_is.html 
sidebar: sidebar 
keywords: nvme, protocol, nonvolatile, memory, express, transport, online, help 
summary: 'NVMe(Nonvolatile Memory Express) 프로토콜은 비휘발성 스토리지 미디어에 액세스하는 데 사용되는 전송 프로토콜입니다.' 
---
= NVMe란 무엇입니까
:icons: font
:imagesdir: ../media/


[role="lead"]
NVMe(Nonvolatile Memory Express) 프로토콜은 비휘발성 스토리지 미디어에 액세스하는 데 사용되는 전송 프로토콜입니다.

NVMe over Fabrics (NVMeoF)는 PCIe 이외의 연결을 통해 NVMe 기반 통신을 가능하게 하는 NVMe에 대한 사양 정의 확장입니다. 이 인터페이스를 통해 외부 스토리지 인클로저를 서버에 연결할 수 있습니다.

NVMe는 플래시 기술에서 고성능 영구 메모리 기술에 이르기까지 비휘발성 메모리로 구축된 스토리지 장치에 효율적으로 액세스할 수 있도록 설계되었습니다. 따라서 하드 디스크 드라이브용으로 설계된 스토리지 프로토콜과 동일한 제한이 없습니다. 플래시 및 SSD(Solid State Device)는 일종의 비휘발성 메모리(NVM)입니다. NVM은 정전 시 콘텐츠를 보관하는 메모리의 한 유형입니다. NVMe는 해당 메모리에 액세스할 수 있는 방법입니다.

NVMe의 이점으로는 데이터 전송을 위한 속도, 생산성, 처리량 및 용량이 증가합니다. 구체적인 특징은 다음과 같습니다.

* NVMe는 최대 64,000개의 대기열을 지원하도록 설계되었습니다.
+
또한 각 대기열에는 최대 64,000개의 동시 명령이 있을 수 있습니다.

* NVMe는 여러 하드웨어 및 소프트웨어 공급업체에서 지원합니다
* NMVe는 빠른 응답 시간을 지원하는 플래시 기술을 통해 생산성이 더 높습니다
* NVMe를 사용하면 SSD로 전송되는 각 "요청"에 대해 여러 데이터 요청을 처리할 수 있습니다.
+
NVMe는 "재퀘스트"를 디코딩하는 데 시간이 더 적게 걸리며 다중 스레드 프로그램에서 스레드 잠금을 요구하지 않습니다.

* NVMe는 CPU 레벨에서 병목 현상을 방지하고 시스템이 확장됨에 따라 대규모 확장성을 지원하는 기능을 지원합니다

