---
permalink: online-help-96-97/concept_types_data_protection_relationships.html 
sidebar: sidebar 
keywords: data, protection, relationship, asynchronous, replication, type, sychronous, online, help 
summary: ONTAP 시스템 관리자는 데이터 보호 및 백업 요구 사항에 따라 우발적, 악의적 또는 재해로 인한 데이터 손실로부터 데이터를 보호할 수 있는 다양한 유형의 보호 관계를 제공합니다. 
---
= 데이터 보호 관계의 유형입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 시스템 관리자는 데이터 보호 및 백업 요구 사항에 따라 우발적, 악의적 또는 재해로 인한 데이터 손실로부터 데이터를 보호할 수 있는 다양한 유형의 보호 관계를 제공합니다.



== 비동기식 복제 유형입니다

* 미러 관계 *

미러 관계는 비동기식 재해 복구를 제공합니다. 데이터 보호 미러링 관계를 사용하면 특정 볼륨에 대한 데이터의 스냅샷 복사본을 주기적으로 생성하여 일반적으로 다른 클러스터에 있는 파트너 볼륨(타겟 볼륨)에 복사한 다음, 해당 스냅샷 복사본을 보존할 수 있습니다. 소스 볼륨의 데이터가 손상되거나 손실된 경우 대상 볼륨의 미러 복사본을 사용하여 최신 스냅샷 복사본 시점에서 데이터를 빠르게 가용성과 복원할 수 있습니다.

미러 관계의 경우 타겟 클러스터에서 실행 중인 ONTAP의 버전이 소스 클러스터에서 실행 중인 ONTAP 버전과 동일하거나 더 최신 버전이어야 합니다. 그러나 버전에 상관없이 유연한 미러 관계는 ONTAP 버전에 따라 달라지지 않습니다. 따라서 소스 클러스터의 ONTAP 버전보다 최신 ONTAP 버전 또는 이전 버전의 ONTAP를 실행 중인 타겟 클러스터나 소스 클러스터의 ONTAP 버전보다 이전 버전의 ONTAP를 실행 중인 타겟 클러스터와 버전에 상관없이 유연한 미러 관계를 생성할 수 있습니다.

[NOTE]
====
* 미러 관계를 설정하려면 SnapMirror 라이센스가 필요합니다.
* 버전에 상관없이 유연한 미러 관계 기능은 ONTAP 8.3 이상에서만 사용할 수 있습니다. Data ONTAP 8.3 이전 버전에서는 버전에 상관없이 유연한 미러 관계를 설정할 수 없습니다.


====
* 볼트 관계 *

볼트 관계를 사용하면 스토리지를 효율적으로 사용하고 백업을 장기간 보존할 수 있습니다. 볼트 관계를 사용하면 볼륨의 선택한 스냅샷 복사본을 대상 볼륨에 백업하고 백업을 유지할 수 있습니다.

[NOTE]
====
볼트 관계를 활성화하려면 SnapMirror 또는 SnapVault 라이센스가 필요합니다.

====
* 미러 및 볼트 관계 *

미러 및 볼트 관계는 소스 볼륨에서 대상 볼륨으로 데이터를 정기적으로 전송하여 데이터를 보호하고 소스 볼륨의 백업을 생성하여 데이터를 장기간 보존할 수 있도록 합니다.

[NOTE]
====
* 미러 및 소산 관계를 활성화하려면 SnapMirror 라이센스가 필요합니다.
* 미러 및 볼트 관계 기능은 ONTAP 8.3.2 이상에서만 사용할 수 있습니다. Data ONTAP 8.3.2 이하에서는 볼륨과 미러 및 볼트 관계를 가질 수 없습니다.


====


== 동기식 복제 정책(SnapMirror Synchronous 라이센스 필요)

* StrictSync * 를 선택합니다

StrictSync 복제 정책은 초기화 후 복제 실패 시 소스 볼륨에 입출력 제한을 적용합니다. StrictSync 복제 정책은 소스 볼륨과 타겟 볼륨이 최신 상태인지 확인하여 데이터 보호를 제공합니다.

[NOTE]
====
* 대상이 DPO(데이터 보호 최적화)가 아닌 경우 소스 클러스터와 타겟 클러스터에 SnapMirror Synchronous 라이센스가 필요합니다.
* 대상이 DPO인 경우 소스 클러스터에 SnapMirror Synchronous 라이센스와 SnapMirror 라이센스가 필요하며 대상 클러스터에 DPO 라이센스가 필요합니다.


====
* 동기화 *

동기화 복제 정책은 초기화 후 복제 실패 시 소스 볼륨에 입출력 제한을 부과하지 않습니다. 동기화 복제 정책은 장애 후 데이터를 대상 볼륨으로 전송하지 않습니다. 소스 볼륨과 타겟 볼륨이 최신 상태인지 확인하려면 재동기화 작업을 수행해야 합니다.

[NOTE]
====
* 대상이 DPO(데이터 보호 최적화)가 아닌 경우 소스 클러스터와 타겟 클러스터에 SnapMirror Synchronous 라이센스가 필요합니다.
* 대상이 DPO인 경우 소스 클러스터에 SnapMirror Synchronous 라이센스와 SnapMirror 라이센스가 필요하며 대상 클러스터에 DPO 라이센스가 필요합니다.


====