---
permalink: online-help-96-97/concept_system_manager_enhancements.html 
sidebar: sidebar 
keywords: ontap, system, manager, enhancement, features 
summary: 이번 릴리즈의 System Manager에서 추가 또는 변경된 기능에 대해 알고 있어야 합니다. 
---
= ONTAP 시스템 관리자의 향상된 기능
:icons: font
:imagesdir: ../media/


[role="lead"]
이번 릴리즈의 System Manager에서 추가 또는 변경된 기능에 대해 알고 있어야 합니다.



== ONTAP 9.6에 추가된 기능 및 향상된 기능

[NOTE]
====
OnCommand 시스템 관리자는 이제 ONTAP 시스템 관리자라고 합니다.

====
* MetroCluster 전환 및 스위치백 작업
+
System Manager 9.6부터는 MetroCluster 스위치오버 및 스위치백 작업을 사용하여 한 클러스터 사이트에서 다른 클러스터 사이트의 작업을 테이크오버할 수 있습니다. 이 기능을 사용하면 재해에 대한 유지 관리 또는 복구를 보다 용이하게 수행할 수 있습니다.

* 추적 파일 액세스
+
새로운 Trace File Access 창을 사용하면 사용자가 CIFS 또는 NFS 프로토콜을 사용하여 SVM에서 파일 및 공유에 액세스하는 데 문제가 있을 때 문제를 진단할 수 있습니다.

* SnapMirror 암호화
+
System Manager 9.6부터는 로컬 클러스터 IPspace용 암호를 생성하고 피어링 관계를 생성할 때 원격 클러스터에서 동일한 암호를 사용할 수 있습니다. 보안상의 이유로 암호를 수정할 수 있습니다.

* FlexCache 기능
+
이제 System Manager에서 FlexCache 볼륨을 생성, 편집, 보기 및 삭제할 수 있습니다.

* Fabric Pool의 향상된 기능
+
이제 Alibaba Cloud 및 Google Cloud를 클라우드 계층으로 사용할 수 있는 오브젝트 저장소로 사용할 수 있습니다. 또한 System Manager에서는 이제 모든 데이터를 클라우드로 계층화하도록 지정할 수 있는 ""모든" 계층화 정책을 지원합니다. 볼륨 360 페이지의 볼륨 성능 탭에서 볼륨의 클라우드 지연 시간을 확인할 수 있도록 기능이 향상되었습니다.

* FlexGroup의 향상된 기능
+
System Manager 9.6부터 볼륨 이름 바꾸기 또는 크기 조정과 같은 기존 FlexGroup 볼륨의 속성을 편집할 수 있습니다.

* SnapLock 볼륨 개선 사항
+
스토리지 QoS 정책 그룹을 생성하거나 수정할 때 성능 기반의 All-Flash 최적화 퍼스낼리티뿐만 아니라 ONTAP Select 프리미엄 시스템의 최소 처리량 한도를 설정할 수 있습니다.





== ONTAP 9.5에 추가된 기능 및 향상된 기능

* 볼륨 암호화
+
이제 FlexVol 볼륨 또는 FlexGroup 볼륨을 편집하는 동안 볼륨 암호화를 활성화할 수 있습니다. 또한 이 기능은 볼륨의 데이터 암호화 키를 변경하기 위한 재키 옵션을 지원하도록 향상되었습니다.

* 클러스터 업데이트
+
System Manager 9.5부터 MetroCluster 구성에서 클러스터를 업데이트할 수 있습니다. 클러스터 업데이트를 제외한 두 클러스터에서 각 작업을 수행해야 합니다.

* 볼륨 복제 정책
+
System Manager 9.5에 StrictSync와 Sync라는 두 가지 새로운 정책이 추가되었습니다. 이러한 정책을 사용하여 복제 실패 시 기본 IO 제한 없이 제로 RPO 복제를 제공할 수 있습니다. 보호 탭을 사용하여 볼륨 보호를 활성화할 수도 있습니다.

* SVM DR
+
SVM(스토리지 가상 시스템) DR(재해 복구)은 SVM의 구성요소 볼륨에 있는 데이터를 복구하고 SVM 구성을 복구하여 SVM 레벨에서 재해 복구 기능을 제공합니다. System Manager를 사용하여 SVM 간에 미러 관계를 생성하고 관리할 수 있으며, 미러 및 소산 관계를 관리할 수 있습니다.

* L2/L3 응용 프로그램이 표시됩니다
+
ONTAP 9.5부터 시스템 관리자는 응용 프로그램 페이지의 다른 호스트 이름 아래에 L2/L3 응용 프로그램을 나열합니다. 호스트 이름을 클릭하면 L2 Cockpit 인터페이스에 새 창이 열립니다. 각 애플리케이션에 대해 System Manager의 IOPS 및 지연 시간 측정도 표시됩니다.

* 가상 IP 지원
+
ONTAP 9.5부터 System Manager는 가상 IP(VIP) LIF에 대한 정보를 표시하지만, System Manager에서 VIP LIF를 생성, 삭제 또는 관리할 수는 없습니다.

* NVMe 하위 시스템 라이센스 요구 사항
+
ONTAP 9.5부터 NVMe에 라이센스가 부여됩니다. System Manager는 라이센스 요구 사항을 지원합니다.

* ONTAP 특유의 데이터 보호 하위 시스템 지원
+
System Manager는 FreeBSD 커널에 상주하는 별도의 커널 개체인 NVMe over Fabric(NVMeoF) 하위 시스템의 사용을 지원합니다. NVMeoF는 PCIe 이외의 연결을 통해 NVMe 기반 통신을 가능하게 하는 NVMe에 대한 사양 정의 확장입니다. 이 인터페이스를 통해 NVMe를 기본 통신 메커니즘으로 사용하면서 외부 스토리지 엔클로저를 직접 또는 스위치를 통해 서버에 연결할 수 있습니다. SAN 구성요소, WAFL 및 RAS 구성요소와 NVMeoF 하위 시스템 인터페이스.

* NVMe 다중 경로 지원
+
ONTAP 9.5부터는 NVMe 프로토콜을 사용하여 HA 쌍의 각 노드에 대해 LIF를 하나 이상 구성해야 합니다. 노드에 대해 2개의 LIF를 정의할 수도 있습니다. ONTAP 9.5로 업그레이드할 때는 NVMe 프로토콜을 사용하여 HA 쌍의 각 노드에 대해 최소 하나의 LIF를 정의해야 합니다.

* FlexGroup 대상 애그리게이트
+
FlexGroup를 생성할 때 모범 사례에 따라 Aggregate가 기본적으로 선택됩니다. All-Flash에 최적화된 스토리지 시스템의 경우 씬 프로비저닝이 기본적으로 설정되고, 다른 스토리지 시스템의 경우 일반 프로비저닝이 기본적으로 설정됩니다. 모범 사례 기본값을 무효화하고 적격한 FabricPool 애그리게이트 목록에서 원하는 항목을 선택할 수 있습니다.

* 공용 SSL 인증서 인증
+
System Manager 9.5부터 SVM과 관련된 공용 SSL 인증서를 볼 수 있습니다. 인증서 세부 정보, 일련 번호, 시작 날짜 및 만료 날짜를 볼 수 있습니다. 인증서를 클립보드에 복사하고 인증서 세부 정보를 이메일로 보낼 수도 있습니다. 또한 vsadmin 사용자 계정을 SVM에 추가하면 HTTP를 애플리케이션으로 사용하고 인증서를 통해 인증된 로그인 방법이 자동으로 포함됩니다.

* FlexVol에서 디렉토리로 표시되는 qtree
+
FlexVol에 qtree와 볼륨이 모두 포함되어 있으면 qtree가 디렉토리로 표시됩니다.

* FlexCache 볼륨
+
FlexCache 볼륨은 System Manager에 FlexGroup로 표시됩니다. 상위 볼륨 세부 정보가 360 페이지에 표시됩니다.





== ONTAP 9.4에 추가된 기능 및 향상된 기능

* NVMe 프로토콜
+
NVM Express(NVMe) 프로토콜은 이제 ONTAP에서 지원되며 System Manager에서 구성할 수 있습니다. NVMe는 기존 iSCSI 또는 FC 프로토콜과 마찬가지로 블록 액세스를 위한 대체 프로토콜입니다.

* 애그리게이트 추천자
+
스토리지 권장 사항을 기반으로 애그리게이트를 생성할 수 있습니다. System Manager는 스토리지 시스템의 구성을 분석하고 생성할 애그리게이트 수, 사용 가능한 노드 및 사용 가능한 스페어 디스크와 같은 스토리지 권장 사항을 제공합니다.

* FabricPool 지원 애그리게이트 기능 향상
+
FabricPool 지원 애그리게이트는 다음 기능을 지원하도록 개선되었습니다.

+
** 외부 용량 계층 메뉴에 대한 새로운 UI 탐색
** 새로운 "자동" 캐싱 정책
** 비활성(콜드) 데이터 지원
** StorageGRID 외부 용량 계층에 대한 오브젝트 저장소 인증서 지원
** Microsoft Azure Blob 스토리지 외부 용량 계층 지원
** 자세한 내용은 클러스터 대시보드의 용량 탭에서 확인할 수 있습니다
** ONTAP Select 지원
** 명령줄 인터페이스(CLI)를 사용하여 생성한 StorageGRID, Amazon AWS S3, Microsoft Azure Blob 스토리지 이외의 외부 용량 계층 보기 지원


* FlexGroup 볼륨 개선 사항
+
FlexGroup 볼륨은 다음과 같은 향상된 기능과 새로운 기능을 제공합니다.

+
** 볼륨 암호화, 스토리지 효율성, QoS 등의 고급 옵션 지원
** 볼륨 보호
** 자세한 내용은 클러스터 대시보드의 보호 탭에서 확인할 수 있습니다


* 단일 노드 클러스터의 중단 없는 업데이트 지원
+
System Manager 9.4부터 단일 노드 클러스터를 업데이트할 수 있습니다. 단일 노드 클러스터 업데이트는 중단되며 업데이트가 진행되는 동안에는 클라이언트 데이터를 사용할 수 없습니다.

* 스냅샷 복사본 구성을 지원합니다
+
기존 스냅샷 정책으로 스케줄을 설정하여 스냅샷 복사본을 구성할 수 있습니다. ONTAP 9.4부터는 FlexVol 볼륨의 Snapshot 복제본 수가 1024개 미만으로 줄어들 수 있습니다.

* 스토리지 효율성 기능의 향상
+
이제 사용된 논리적 공간의 비율과 논리적 공간 보고 상태가 System Manager Volumes 창에 표시됩니다.

* SMB 멀티 채널 지원
+
SMB 프로토콜을 사용하면 SMB3.0 세션과 전송 연결 간에 여러 채널을 설정할 수 있습니다. 특히 성능, 내결함성 및 복구 성능을 향상시킬 수 있습니다.





== ONTAP 9.3에 추가된 기능 및 향상된 기능

* 웹 서비스에 대한 SAML 인증 지원
+
ONTAP 9.3부터는 SAML(Security Assertion Markup Language) 인증을 사용하여 웹 서비스에 대한 MFA(Multifactor Authentication)를 구성할 수 있습니다. SPI(서비스 프로세서 인프라), ONTAP API 및 System Manager에 SAML 인증을 사용할 수 있습니다.

* 애플리케이션 인식 데이터 관리
+
애플리케이션 인식 데이터 관리는 스토리지 설정을 단순화하고 애플리케이션과 관련된 입력을 제공하여 주요 애플리케이션에 몇 분 이내에 데이터를 제공할 수 있도록 합니다.

* GUI 및 탐색을 수정했습니다
+
그래픽 사용자 인터페이스(GUI)는 사용자에게 보다 직관적인 환경을 제공하도록 변경되었습니다.

* ONTAP 시스템과 SolidFire 시스템 간의 보호 관계 깨기 지원
+
ONTAP 9.3부터는 System Manager를 사용하여 ONTAP 시스템과 SolidFire 스토리지 시스템 간의 SnapMirror 관계를 끊을 수 있습니다.

* 클러스터 피어링 및 SVM 피어링을 간소화합니다
+
System Manager에서 제공하는 향상된 기능을 통해 클러스터 및 SVM 간에 피어 관계를 간편하게 구성할 수 있습니다.

* 사전 구성된 템플릿을 사용하여 SVM 프로비저닝 지원
+
ONTAP 9.3부터는 사전 구성된 템플릿을 사용하여 SVM을 생성하고 프로비저닝할 수 있습니다.

* 향상된 클러스터 대시보드
+
클러스터 대시보드가 향상되어 핸드헬드 장치에서 다양한 정보를 볼 수 있도록 응답 속도가 향상되었습니다.


