---
permalink: online-help-96-97/concept_license_types_entitlement_risk.html 
sidebar: sidebar 
keywords: license, types, entitlement, risk, cluster, online, help 
summary: 다양한 라이센스 유형 및 관련 자격 위험을 이해하면 클러스터의 라이센스와 관련된 위험을 관리할 수 있습니다. 
---
= 라이센스 유형 및 권한 부여 위험
:icons: font
:imagesdir: ../media/


[role="lead"]
다양한 라이센스 유형 및 관련 자격 위험을 이해하면 클러스터의 라이센스와 관련된 위험을 관리할 수 있습니다.



== 사용권 유형

패키지에는 다음 유형의 라이센스 중 하나 이상이 클러스터에 설치되어 있을 수 있습니다.

* 노드 잠김 라이센스 또는 표준 라이센스
+
특정 시스템 일련 번호(_controller 일련 번호 _ 라고도 함)가 있는 노드에 대해 노드 잠김 라이센스가 발급됩니다. 이 라이센스는 일련 번호가 일치하는 노드에 대해서만 유효합니다.

+
노드 잠금 라이센스를 설치하면 노드에 라이센스가 부여된 기능이 부여됩니다. 클러스터에 라이센스가 부여된 기능을 사용하려면 해당 기능에 대해 하나 이상의 노드에 라이센스가 있어야 합니다. 기능에 대한 사용 권한이 없는 노드에서 라이센스가 부여된 기능을 사용하지 못할 수 있습니다.

+
ONTAP 8.2 이상 릴리즈에서는 Data ONTAP 8.2 이전 버전에 설치된 라이센스를 표준 라이센스로 처리합니다. 따라서 ONTAP 8.2 이상 릴리즈에서는 클러스터의 모든 노드에 이전에 라이센스가 부여된 기능이 포함된 패키지의 표준 라이센스가 자동으로 부여됩니다.

* 마스터 또는 사이트 라이센스
+
마스터 또는 사이트 라이센스가 특정 시스템 일련 번호에 연결되지 않았습니다. 사이트 라이센스를 설치하면 클러스터의 모든 노드에 라이센스가 부여된 기능이 부여됩니다.

+
클러스터에 마스터 라이센스가 있고 클러스터에서 노드를 제거할 경우 노드에 사이트 라이센스가 포함되지 않으며 노드에 라이센스가 부여된 기능이 더 이상 제공되지 않습니다. 마스터 라이센스가 있는 클러스터에 노드를 추가하면 해당 노드는 사이트 라이센스에 의해 부여된 기능을 자동으로 사용할 수 있습니다.

* 데모 또는 임시 라이센스
+
데모 또는 임시 라이센스는 일정 기간이 지나면 만료됩니다. 이 라이센스를 사용하면 사용 권한을 구입하지 않고도 특정 소프트웨어 기능을 사용할 수 있습니다. 임시 라이센스는 클러스터 전체 라이센스이며 노드의 특정 일련 번호에 연결되지 않습니다.

+
클러스터에 패키지에 대한 임시 라이센스가 있고 클러스터에서 노드를 제거하는 경우 노드에 평가판 라이센스가 포함되지 않습니다.

* 용량 라이센스(ONTAP Select 및 FabricPool만 해당)
+
ONTAP Select 인스턴스는 사용자가 관리하려는 데이터 양에 따라 라이센스가 부여됩니다. 예를 들어, 사용자가 10TB 용량 라이센스를 구입하여 ONTAP Select에서 최대 10TB의 데이터를 관리할 수 있습니다. ONTAP Select이 관리할 수 있는 라이센스가 있는 것보다 더 많은 스토리지 용량이 시스템에 연결된 경우 ONTAP Select가 작동하지 않습니다. 기본적으로 ONTAP Select 인스턴스에 연결할 수 있는 최대 스토리지 용량은 용량 라이센스(예: 5TB 용량 라이센스, 10TB 용량 라이센스 등)를 구입하여 설치할 때까지 2TB입니다.

+
ONTAP 9.2부터 FabricPool 지원 애그리게이트는 타사 스토리지 계층(예: AWS)과 함께 용량 라이센스를 필요로 합니다. FabricPool 용량 라이센스는 클라우드 계층 스토리지에 저장할 수 있는 데이터의 양을 정의합니다.





== 소유 권한 위험

자격 위험이 노드 잠김 라이센스의 비균일 설치 때문에 발생합니다. 노드 잠김 라이센스가 모든 노드에 설치된 경우 권한 부여 위험이 없습니다.

소유 권한 위험 수준은 특정 조건에 따라 고위험, 중간 위험, 위험 없음 또는 알 수 없는 위험이 될 수 있습니다.

* 높은 위험
+
** 특정 노드에 사용량이 있지만 노드 잠김 라이센스가 해당 노드에 설치되어 있지 않은 경우
** 클러스터에 설치된 데모 라이센스가 만료되고 노드에 사용량이 있는 경우


+
[NOTE]
====
사이트 라이센스가 클러스터에 설치된 경우 권한 부여 위험이 높아지지 않습니다.

====
* 중간 위험도
+
사이트 라이센스가 설치되어 있지 않고 노드 잠김 라이센스가 클러스터의 노드에 불균일하게 설치되어 있는 경우

* 위험이 없습니다
+
노드 잠김 라이센스가 모든 노드에 설치되어 있거나 사이트 라이센스가 사용 여부와 관계없이 클러스터에 설치되어 있으면 권한 부여 위험이 없습니다.

* 알 수 없음
+
API가 클러스터 또는 클러스터의 노드에 연결된 권한 부여 위험과 관련된 데이터를 검색할 수 없는 경우가 있을 경우 위험을 알 수 없습니다.


