---
permalink: online-help-96-97/concept_what_snapvault_backup_is.html 
sidebar: sidebar 
keywords: baseline, transfer, defined, snapvault, snapshot, copy, online, help 
summary: SnapVault 백업은 FlexVol 볼륨의 스냅샷 복사본 모음으로, 운영 데이터를 사용할 수 없는 경우 데이터를 복원할 수 있습니다. 스냅샷 복사본은 스냅샷 정책을 기반으로 생성됩니다. SnapVault 백업은 스케줄 및 SnapVault 정책 규칙에 따라 스냅샷 복사본을 백업합니다. 
---
= SnapVault 백업이란
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapVault 백업은 FlexVol 볼륨의 스냅샷 복사본 모음으로, 운영 데이터를 사용할 수 없는 경우 데이터를 복원할 수 있습니다. 스냅샷 복사본은 스냅샷 정책을 기반으로 생성됩니다. SnapVault 백업은 스케줄 및 SnapVault 정책 규칙에 따라 스냅샷 복사본을 백업합니다.

SnapVault 백업은 테이프 백업을 오프로드하는 데 사용할 수 있는 D2D 백업 솔루션입니다. 시스템에서 데이터 손실 또는 손상이 발생할 경우, 백업 데이터를 SnapVault 보조 볼륨에서 기존 테이프 백업 및 복원 작업에 비해 더 적은 다운타임 및 불확실성으로 복원할 수 있습니다.

다음 용어는 SnapVault 백업을 설명하는 데 사용됩니다.

* * 기본 전송 *
+
운영 스토리지 볼륨의 초기 전체 백업을 보조 시스템의 해당 볼륨에 수행합니다.

* * 보조 볼륨 *
+
운영 볼륨에서 데이터를 백업하는 볼륨입니다. 이러한 볼륨은 캐스케이드 또는 팬아웃 백업 구성의 2차 또는 3차(이상) 대상이 될 수 있습니다. SnapVault 2차 시스템은 장기 스토리지와 가능한 복원 작업을 위한 스냅샷 복사본을 유지합니다.

* * 증분 전송 *
+
마지막 전송 작업 이후 운영 데이터의 변경 사항만 포함된 보조 시스템에 대한 후속 백업

* * SnapMirror 레이블 *
+
SnapVault 백업에서 선택 및 보존을 위해 스냅샷 복사본을 식별하는 속성입니다. 각 SnapVault 정책은 기본 볼륨에서 스냅샷 복사본을 선택하고 지정된 SnapMirror 레이블과 일치하는 스냅샷 복사본을 전송하기 위한 규칙을 구성합니다.

* * 스냅샷 복사본 *
+
소스 볼륨의 백업 이미지로, 할당된 정책에 따라 수동 또는 자동으로 생성됩니다. 기본 스냅샷 복사본에는 보호할 전체 소스 데이터의 복사본이 포함됩니다. 후속 스냅샷 복사본에는 소스 데이터의 차등 복사본이 포함됩니다. 스냅샷 복사본은 소스 볼륨 또는 다른 SVM(스토리지 가상 머신) 또는 클러스터의 다른 타겟 볼륨에 저장할 수 있습니다.

+
스냅샷 복사본은 각 소스 시스템의 볼륨 데이터 상태를 캡처합니다. SnapVault 및 미러 관계의 경우 이 데이터가 타겟 볼륨으로 전송됩니다.

* * 기본 볼륨 *
+
백업할 데이터가 들어 있는 볼륨입니다. 캐스케이드 또는 팬아웃 백업 배포에서 주 볼륨은 SnapVault 소스가 있는 체인에 관계없이 SnapVault 백업으로 백업되는 볼륨입니다. A가 B와 미러 관계가 있고 B가 C와 SnapVault 관계가 있는 계단식 배열 구성에서는 B가 체인의 2차 대상이더라도 SnapVault 백업의 소스로 사용됩니다.

* * SnapVault 관계 *
+
운영 볼륨과 2차 볼륨 간의 SnapVault 관계로 구성된 백업 관계입니다.



* 관련 정보 *

xref:reference_protection_window.adoc[보호 윈도우]
