---
permalink: online-help-96-97/reference_quotas_window.html 
sidebar: sidebar 
keywords: quota, window, create, display, manage, information, online, help 
summary: Quotas 창을 사용하여 할당량에 대한 정보를 생성, 표시 및 관리할 수 있습니다. 
---
= 할당량 창
:icons: font
:imagesdir: ../media/


[role="lead"]
Quotas 창을 사용하여 할당량에 대한 정보를 생성, 표시 및 관리할 수 있습니다.



== 탭

* * 사용자 정의 할당량 *
+
사용자 정의 할당량 * 탭을 사용하여 생성한 할당량에 대한 세부 정보를 보고 할당량을 생성, 편집 또는 삭제할 수 있습니다.

* * 할당량 보고서 *
+
할당량 보고서 탭을 사용하여 공간과 파일 사용량을 확인하고 활성 할당량의 공간 및 파일 한도를 편집할 수 있습니다.

* * 볼륨의 할당량 상태 *
+
볼륨 탭의 할당량 상태 탭을 사용하여 할당량 상태를 확인하고 할당량을 설정하거나 해제할 수 있으며 할당량 크기를 조정할 수 있습니다.





== 명령 버튼

* * 생성 *
+
할당량을 생성할 수 있는 할당량 생성 마법사를 엽니다.

* * 한도 편집 *
+
선택한 할당량의 설정을 편집할 수 있는 제한 편집 대화 상자를 엽니다.

* * 삭제 *
+
할당량 목록에서 선택한 할당량을 삭제합니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





== 사용자 정의 할당량 목록

할당량 목록에 각 할당량의 이름과 스토리지 정보가 표시됩니다.

* * 볼륨 *
+
할당량이 적용되는 볼륨을 지정합니다.

* * Qtree *
+
할당량과 연결된 qtree를 지정합니다. ""모든 qtree""는 할당량이 모든 qtree와 연결됨을 나타냅니다.

* * 유형 *
+
할당량 유형(사용자, 그룹 또는 트리)을 지정합니다.

* * 사용자/그룹 *
+
할당량과 연결된 사용자 또는 그룹을 지정합니다. "모든 사용자"는 할당량이 모든 사용자와 연결되어 있음을 나타냅니다. "모든 그룹"은 할당량이 모든 그룹에 연결되었음을 나타냅니다.

* * 할당량 타겟 *
+
할당량이 할당된 타겟의 유형을 지정합니다. 타겟은 qtree, 사용자 또는 그룹이 될 수 있습니다.

* * 공간 하드 제한값 *
+
하드 할당량에 적용되는 디스크 공간 제한을 지정합니다.

+
이 필드는 기본적으로 숨겨져 있습니다.

* * 공간 소프트 제한값 *
+
소프트 할당량에 적용되는 디스크 공간 제한을 지정합니다.

+
이 필드는 기본적으로 숨겨져 있습니다.

* * 임계값 *
+
임계값 할당량에 적용되는 디스크 공간 제한을 지정합니다.

+
이 필드는 기본적으로 숨겨져 있습니다.

* * 파일 하드 제한값 *
+
하드 할당량의 최대 파일 수를 지정합니다.

+
이 필드는 기본적으로 숨겨져 있습니다.

* * 파일 소프트 제한값 *
+
소프트 할당량의 최대 파일 수를 지정합니다.

+
이 필드는 기본적으로 숨겨져 있습니다.





== 세부 정보 영역

할당량 목록 아래의 영역에는 할당량 오류, 공간 사용량 및 제한, 파일 사용량 및 제한과 같은 할당량 세부 정보가 표시됩니다.

* 관련 정보 *

xref:task_creating_quotas.adoc[할당량 생성 중]

xref:task_deleting_quotas.adoc[할당량을 삭제하는 중입니다]

xref:task_editing_quota_limits.adoc[할당량 한도 편집 중]

xref:task_activating_or_deactivating_quotas.adoc[할당량 활성화 또는 비활성화]

xref:task_resizing_quotas.adoc[할당량 크기 조정]
