---
permalink: online-help-96-97/reference_name_mapping_window.html 
sidebar: sidebar 
keywords: name, map, window, command, button, online, help, group 
summary: 이름 매핑 창을 사용하여 이름 매핑 항목을 지정하여 다른 플랫폼의 사용자를 매핑할 수 있습니다. 
---
= 이름 매핑 창
:icons: font
:imagesdir: ../media/


[role="lead"]
이름 매핑 창을 사용하여 이름 매핑 항목을 지정하여 다른 플랫폼의 사용자를 매핑할 수 있습니다.



== 이름 매핑

이름 매핑을 만들고 사용하여 UNIX 사용자를 Windows 사용자, Windows 사용자, UNIX 사용자 또는 Kerberos 사용자를 UNIX 사용자에게 매핑할 수 있습니다.



== 명령 버튼

* * 추가 *
+
이름 매핑 항목 추가 대화 상자를 엽니다. 이 대화 상자에서 SVM(스토리지 가상 머신)에 이름 매핑을 생성할 수 있습니다.

* * 편집 *
+
SVM에서 이름 매핑을 편집할 수 있는 이름 매핑 항목 편집 대화 상자를 엽니다.

* * 삭제 *
+
이름 매핑 항목을 삭제할 수 있는 이름 매핑 항목 삭제 대화 상자를 엽니다.

* * 교환 *
+
선택한 두 이름 매핑 항목의 위치를 변경할 수 있는 이름 매핑 항목 바꾸기 대화 상자를 엽니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





== 이름 매핑 목록

* * 위치 *
+
우선 순위 목록에서 이름 매핑의 위치를 지정합니다. 이름 매핑은 우선 순위 목록에 있는 순서대로 적용됩니다.

* * 패턴 *
+
일치시켜야 하는 사용자 이름 패턴을 지정합니다.

* * 교체 *
+
사용자 이름의 대체 패턴을 지정합니다.

* * 방향 *
+
이름 매핑의 방향을 지정합니다. Kerberos-UNIX 이름 매핑의 경우 KRB_UNIX, Windows-UNIX 이름 매핑의 경우 WIN_UNIX, UNIX-Windows 이름 매핑의 경우 UNIX_WIN을 사용할 수 있습니다.





== 명령 버튼

* * 추가 *
+
SVM에서 그룹 매핑을 생성할 수 있는 그룹 매핑 항목 추가 대화 상자를 엽니다.

* * 편집 *
+
SVM에서 그룹 매핑을 편집할 수 있는 그룹 매핑 항목 편집 대화 상자를 엽니다.

* * 삭제 *
+
그룹 매핑 항목을 삭제할 수 있는 그룹 매핑 항목 삭제 대화 상자를 엽니다.

* * 교환 *
+
선택한 두 그룹 매핑 항목의 위치를 변경할 수 있는 그룹 매핑 항목 바꾸기 대화 상자를 엽니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





== 그룹 매핑 목록

* * 위치 *
+
우선 순위 목록에서 그룹 매핑의 위치를 지정합니다. 그룹 매핑은 우선 순위 목록에 있는 순서대로 적용됩니다.

* * 패턴 *
+
일치시켜야 하는 사용자 이름 패턴을 지정합니다.

* * 교체 *
+
사용자 이름의 대체 패턴을 지정합니다.

* * 방향 *
+
그룹 매핑의 방향을 지정합니다. 가능한 값은 Kerberos-UNIX 그룹 매핑의 KRB_UNIX, Windows-UNIX 그룹 매핑의 WIN_UNIX, UNIX-Windows 그룹 매핑의 UNIX_WIN입니다.


