---
permalink: online-help-96-97/reference_efficiency_policies.html 
sidebar: sidebar 
keywords: efficiency, policies, window, command, buttons, online, help 
summary: 효율성 정책 창을 사용하여 효율성 정책에 대한 정보를 생성, 표시 및 관리할 수 있습니다. 
---
= 효율성 정책 창
:icons: font
:imagesdir: ../media/


[role="lead"]
효율성 정책 창을 사용하여 효율성 정책에 대한 정보를 생성, 표시 및 관리할 수 있습니다.



== 명령 버튼

* * 추가 *
+
지정된 기간(스케줄 기반) 또는 볼륨 데이터의 변경이 지정된 임계값(임계값 기반)에 도달할 때 볼륨에 대해 중복 제거 작업을 실행할 수 있는 효율성 정책 추가 대화 상자를 엽니다.

* * 편집 *
+
효율성 정책 편집 대화 상자를 엽니다. 이 대화 상자에서 중복제거 작업의 스케줄, 임계값, QoS 유형, 최대 실행 시간을 수정할 수 있습니다.

* * 삭제 *
+
선택한 효율성 정책을 삭제할 수 있는 효율성 정책 삭제 대화 상자를 엽니다.

* * 상태 *
+
선택한 효율성 정책을 활성화 또는 비활성화하는 옵션을 제공하는 드롭다운 메뉴를 엽니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





== 효율성 정책 목록

* * 정책 *
+
효율성 정책의 이름을 지정합니다.

* * 상태 *
+
효율성 정책의 상태를 지정합니다. 상태는 다음 중 하나일 수 있습니다.

+
** 활성화됨
+
중복 제거 작업에 효율성 정책을 할당할 수 있도록 지정합니다.

** 사용 안 함
+
효율성 정책이 비활성화되도록 지정합니다. 상태 드롭다운 메뉴를 사용하여 정책을 사용하도록 설정하고 나중에 중복 제거 작업에 할당할 수 있습니다.



* * 실행 기준 *
+
스토리지 효율성 정책을 스케줄에 따라 실행할지 또는 임계값(변경 로그 임계값)을 기반으로 실행할지 여부를 지정합니다.

* * QoS 정책 *
+
스토리지 효율성 정책의 QoS 유형을 지정합니다. QoS 유형은 다음 중 하나일 수 있습니다.

+
** 배경
+
QoS 정책이 백그라운드에서 실행되고 있음을 지정함으로써 클라이언트 작업에 대한 잠재적인 성능 영향을 줄입니다.

** 최선의 노력
+
QoS 정책이 최선 노력 기반으로 실행되도록 지정합니다. 이를 통해 시스템 리소스 활용률을 최대화할 수 있습니다.



* * 최대 런타임 *
+
효율성 정책의 최대 런타임 기간을 지정합니다. 이 값을 지정하지 않으면 작업이 완료될 때까지 효율성 정책이 실행됩니다.





== 세부 정보 영역

효율성 정책 목록 아래의 영역에는 일정 이름, 일정 기반 정책의 일정 세부 정보, 임계값 기반 정책의 임계값 등 선택한 효율성 정책에 대한 추가 정보가 표시됩니다.
