---
permalink: online-help-96-97/reference_export_policies.html 
sidebar: sidebar 
keywords: export, policy, window, online, help, command, button, assigned, exports 
summary: 엑스포트 정책 창을 사용하면 엑스포트 정책과 관련 엑스포트 규칙에 대한 정보를 생성, 보기, 관리할 수 있습니다. 
---
= 엑스포트 정책 창
:icons: font
:imagesdir: ../media/


[role="lead"]
엑스포트 정책 창을 사용하면 엑스포트 정책과 관련 엑스포트 규칙에 대한 정보를 생성, 보기, 관리할 수 있습니다.



== 엑스포트 정책

엑스포트 정책 창에서는 SVM(스토리지 가상 머신)에 대해 생성된 엑스포트 정책을 확인하고 관리할 수 있습니다.

* * 명령 버튼 *
+
** 생성
+
엑스포트 정책을 생성하고 엑스포트 규칙을 추가할 수 있는 엑스포트 정책 생성 대화 상자를 엽니다. 기존 SVM에서 엑스포트 규칙을 복사할 수도 있습니다.

** 이름 바꾸기
+
선택한 엑스포트 정책의 이름을 바꿀 수 있는 정책 이름 바꾸기 대화 상자를 엽니다.

** 삭제
+
선택한 엑스포트 정책을 삭제할 수 있는 엑스포트 정책 삭제 대화 상자를 엽니다.

** 새로 고침
+
창에서 정보를 업데이트합니다.







== 규칙 내보내기 탭

규칙 내보내기 탭에서는 특정 엑스포트 정책에 대해 생성된 엑스포트 규칙에 대한 정보를 볼 수 있습니다. 규칙을 추가, 편집 및 삭제할 수도 있습니다.

* * 명령 버튼 *
+
** 추가
+
선택한 엑스포트 정책에 엑스포트 규칙을 추가할 수 있는 엑스포트 규칙 생성 대화 상자를 엽니다.

** 편집
+
선택한 내보내기 규칙의 특성을 수정할 수 있는 내보내기 규칙 수정 대화 상자를 엽니다.

** 삭제
+
선택한 내보내기 규칙을 삭제할 수 있는 내보내기 규칙 삭제 대화 상자를 엽니다.

** 위로 이동
+
선택한 내보내기 규칙의 규칙 인덱스를 위로 이동합니다.

** 아래로 이동합니다
+
선택한 내보내기 규칙의 규칙 인덱스를 아래로 이동합니다.

** 새로 고침
+
창에서 정보를 업데이트합니다.



* * 규칙 목록 내보내기 *
+
** 규칙 색인
+
내보내기 규칙이 처리되는 우선 순위를 지정합니다. 위로 이동 및 아래로 이동 단추를 사용하여 우선 순위를 선택할 수 있습니다.

** 클라이언트
+
규칙을 적용할 클라이언트를 지정합니다.

** 액세스 프로토콜
+
내보내기 규칙에 지정된 액세스 프로토콜을 표시합니다.

+
액세스 프로토콜을 지정하지 않은 경우 기본값 ""Any""가 고려됩니다.

** 읽기 전용 규칙입니다
+
읽기 전용 액세스에 대해 하나 이상의 보안 유형을 지정합니다.

** 읽기/쓰기 규칙
+
읽기/쓰기 액세스에 사용할 보안 유형을 하나 이상 지정합니다.

** 고급 사용자 액세스
+
고급 사용자 액세스에 대한 보안 유형을 지정합니다.







== 할당된 개체 탭

Assigned Objects 탭에서는 선택한 엑스포트 정책에 할당된 볼륨 및 qtree를 볼 수 있습니다. 볼륨이 암호화되었는지 여부를 확인할 수도 있습니다.
