---
permalink: online-help-96-97/reference_qtrees_window.html 
sidebar: sidebar 
keywords: qtree, online, help, window, command, button 
summary: Qtree 창을 사용하여 Qtree에 대한 정보를 생성, 표시 및 관리할 수 있습니다. 
---
= Qtree 창
:icons: font
:imagesdir: ../media/


[role="lead"]
Qtree 창을 사용하여 Qtree에 대한 정보를 생성, 표시 및 관리할 수 있습니다.



== 명령 버튼

* * 생성 *
+
새 qtree를 생성할 수 있는 Create Qtree 대화 상자를 엽니다.

* * 편집 *
+
Qtree 편집 대화 상자를 엽니다. 이 대화 상자에서 보안 스타일을 변경하고 qtree에서 oplocks(편의적 잠금)를 설정하거나 해제할 수 있습니다.

* * 수출 정책 변경 *
+
하나 이상의 qtree를 새 엑스포트 정책 또는 기존 엑스포트 정책에 할당할 수 있는 엑스포트 정책 대화 상자를 엽니다.

* * 삭제 *
+
선택한 qtree를 삭제합니다.

+
선택한 qtree의 상태가 정상이 아닌 경우 이 버튼이 비활성화됩니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





== qtree 목록

qtree 목록에는 qtree가 있는 볼륨과 qtree 이름이 표시됩니다.

* * 이름 *
+
qtree의 이름이 표시됩니다.

* * 볼륨 *
+
qtree가 상주하는 볼륨의 이름을 표시합니다.

* * 보안 스타일 *
+
qtree의 보안 유형을 지정합니다.

* * 상태 *
+
qtree의 현재 상태를 지정합니다.

* oplocks *
+
qtree에 대해 oplocks 설정을 사용할지 여부를 지정합니다.

* * 정책 내보내기 *
+
qtree가 할당된 엑스포트 정책의 이름을 표시합니다.





== 세부 정보 영역

* * 세부 정보 탭 *
+
qtree가 포함된 볼륨의 마운트 경로, 엑스포트 정책에 대한 세부 정보, 엑스포트 정책 규칙 등 선택한 qtree에 대한 자세한 정보를 표시합니다.



* 관련 정보 *

xref:task_creating_qtrees.adoc[qtree 생성]

xref:task_deleting_qtrees.adoc[Qtree 삭제]

xref:task_editing_qtrees.adoc[qtree 편집]
