---
permalink: online-help-96-97/reference_system_health_window.html 
sidebar: sidebar 
keywords: system, alerts, command, buttons, window, online, help 
summary: 시스템 알림 창을 사용하여 시스템 상태 알림에 대해 자세히 알아볼 수 있습니다. 창에서 경고를 확인, 삭제 및 억제할 수도 있습니다. 
---
= 시스템 경고 창
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템 알림 창을 사용하여 시스템 상태 알림에 대해 자세히 알아볼 수 있습니다. 창에서 경고를 확인, 삭제 및 억제할 수도 있습니다.



== 명령 버튼

* * 확인 *
+
선택한 경고를 확인하여 문제가 해결되고 있음을 알리고 단추를 클릭한 사람을 ""확인자"로 식별할 수 있습니다.

* * 기능 억제 *
+
선택한 경고를 억제하여 시스템이 사용자에게 동일한 경고를 다시 알리지 않고 사용자를 "서프레서"로 식별할 수 있습니다.

* * 삭제 *
+
선택한 경고를 삭제합니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





== 알림 목록

* 하위 시스템(번호 알림 수) *
+
알림이 생성된 SAS 연결, 스위치 상태, CIFS NDO 또는 MetroCluster와 같은 서브시스템의 이름을 표시합니다.

* * 경고 ID *
+
경고 ID를 표시합니다.

* * 노드 *
+
알림이 생성된 노드의 이름을 표시합니다.

* * 심각도 *
+
알림의 심각도를 알 수 없음, 기타, 정보, 성능 저하, 경미함, 중대, 중대 또는 치명적

* * 리소스 *
+
알림을 생성한 리소스(예: 특정 쉘프 또는 디스크)를 표시합니다.

* 시간 *
+
알림이 생성된 시간을 표시합니다.





== 세부 정보 영역

세부 정보 영역에는 경고가 생성된 시간 및 경고가 확인되었는지 여부와 같은 알림에 대한 자세한 정보가 표시됩니다. 이 영역에는 경고에 의해 생성된 조건의 가능한 원인 및 가능한 영향에 대한 정보와 경고에 의해 보고된 문제를 해결하기 위한 권장 조치가 포함됩니다.

* 관련 정보 *

xref:task_acknowledging_system_health_alerts.adoc[시스템 상태 알림을 확인합니다]

xref:task_suppressing_system_health_alerts.adoc[시스템 상태 알림을 표시하지 않습니다]

xref:task_deleting_system_health_alerts.adoc[시스템 상태 알림을 삭제하는 중입니다]
