---
permalink: online-help-96-97/reference_cluster_peers_window.html 
sidebar: sidebar 
keywords: cluster, peer, window, command, button, online, help 
summary: 클러스터 피어 창을 사용하여 피어 클러스터 관계를 관리할 수 있으며, 이 창에서 클러스터 간에 데이터를 이동할 수 있습니다. 
---
= Cluster 피어의 창입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 피어 창을 사용하여 피어 클러스터 관계를 관리할 수 있으며, 이 창에서 클러스터 간에 데이터를 이동할 수 있습니다.



== 명령 버튼

* * 생성 *
+
원격 클러스터와의 관계를 생성할 수 있는 클러스터 피어링 생성 대화 상자를 엽니다.

* * 편집 *
+
다음과 같은 선택 항목이 있는 드롭다운 메뉴를 표시합니다.

+
** * 로컬 클러스터 암호 *
+
Edit Local Cluster Passphrase 대화 상자를 엽니다. 이 대화 상자에서는 로컬 클러스터를 검증하기 위해 새 암호를 입력할 수 있습니다.

** 피어 클러스터 네트워크 매개 변수 *
+
IPspace를 수정하고 인터클러스터 LIF IP 주소를 추가하거나 제거할 수 있는 피어 클러스터 네트워크 매개 변수 편집 대화 상자를 엽니다.

+
여러 IP 주소를 쉼표로 구분하여 추가할 수 있습니다.

** * 암호화 변경 *
+
선택한 피어 클러스터에 대한 암호화 변경 대화 상자를 엽니다. 피어링된 관계 암호화를 변경하는 동안 새 암호를 생성하거나 원격 피어링된 클러스터에서 이미 생성된 암호를 제공할 수 있습니다.

+
암호화 상태가 "해당 없음"인 경우 이 작업을 사용할 수 없습니다.



* * 삭제 *
+
선택한 피어 클러스터 관계를 삭제할 수 있는 클러스터 피어 관계 삭제 대화 상자를 엽니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.

* * SVM 권한 관리 *
+
SVM이 SVM 피어링 요청을 자동으로 수용할 수 있도록 지원

* * 피어링 패스구문 생성 *
+
IPspace를 지정하고, 암호 유효 기간을 설정하고, 사용 권한이 부여된 SVM을 지정하여 로컬 클러스터 IPspace에 대한 암호를 생성할 수 있습니다.

+
원격 클러스터에서 피어링을 위해 동일한 암호를 사용합니다.





== 피어 클러스터 목록

* 피어 클러스터 *
+
관계에서 피어 클러스터의 이름을 지정합니다.

* * 가용성 *
+
피어 클러스터를 통신에 사용할 수 있는지 여부를 지정합니다.

* * 인증 상태 *
+
피어 클러스터의 인증 여부를 지정합니다.

* * 로컬 클러스터 IPspace *
+
로컬 클러스터 피어 관계와 연결된 IPspace를 표시합니다.

* * 피어 클러스터 인터클러스터 IP 주소 *
+
인터클러스터 피어 관계와 연결된 IP 주소를 표시합니다.

* * 마지막 업데이트 시간 *
+
피어 클러스터가 마지막으로 수정된 시간을 표시합니다.

* * 암호화 *
+
피어링 관계의 암호화 상태를 표시합니다.

+
[NOTE]
====
System Manager 9.6부터는 두 클러스터 간의 피어링 관계를 설정할 때 피어링을 기본적으로 암호화합니다

====
+
** * 해당 없음 *: 암호화는 관계에 적용되지 않습니다.
** * 없음 *: 피어링 관계는 암호화되지 않습니다.
** * TLS_PSK *: 피어링 관계가 암호화됩니다.



