---
permalink: online-help-96-97/reference_nvme_subsystems_window.html 
sidebar: sidebar 
keywords: nvme, subsystems, window, table, toolbar, online, help, cluster 
summary: NVMe 하위 시스템 창에는 기본적으로 클러스터의 NVMe 하위 시스템의 인벤토리 목록이 표시됩니다. 목록을 필터링하여 SVM과 관련된 하위 시스템만 표시할 수 있습니다. 이 창에서는 NVMe 서브시스템을 생성, 편집 또는 삭제할 수도 있습니다. Storage NVMe Subsystems를 선택하면 이 창에 액세스할 수 있습니다. 
---
= NVMe 하위 시스템 창
:icons: font
:imagesdir: ../media/


[role="lead"]
NVMe 하위 시스템 창에는 기본적으로 클러스터의 NVMe 하위 시스템의 인벤토리 목록이 표시됩니다. 목록을 필터링하여 SVM과 관련된 하위 시스템만 표시할 수 있습니다. 이 창에서는 NVMe 서브시스템을 생성, 편집 또는 삭제할 수도 있습니다. 스토리지 * > * NVMe * > * 하위 시스템 * 을 선택하여 이 창에 액세스할 수 있습니다.

* <<GUID-1E417C67-1F31-4FA5-AAA7-2D5BB298C6AB,NVMe 하위 시스템 표>>
* <<SECTION_819274C0AB2341B0915167A78A41F1D8,도구 모음>>




== NVMe 하위 시스템 표

NVMe 하위 시스템 표에는 클러스터 내 NVMe 하위 시스템의 인벤토리가 나와 있습니다. SVM * 필드의 드롭다운 메뉴를 사용하여 SVM을 선택하여 해당 SVM과 관련된 NVMe 서브시스템만 표시되도록 목록을 개선할 수 있습니다. 검색 * 필드 및 * 필터링 * 드롭다운 메뉴를 사용하여 목록을 추가로 사용자 지정할 수 있습니다.

NVMe 하위 시스템 표에는 다음 열이 포함됩니다.

* * (확인란) *
+
작업을 수행할 하위 시스템을 지정할 수 있습니다.

+
확인란을 클릭하여 하위 시스템을 선택한 다음 수행할 도구 모음에서 작업을 클릭합니다.

* * 이름 *
+
하위 시스템의 이름을 표시합니다.

+
검색 * 필드에 하위 시스템의 이름을 입력하여 하위 시스템을 검색할 수 있습니다.

* * 호스트 OS *
+
서브시스템과 연결된 호스트 OS의 이름을 표시합니다.

* * 호스트 NQN *
+
컨트롤러에 연결된 NVMe 정규화된 이름(NQN)을 표시합니다. 여러 개의 NQN이 표시되면 쉼표로 구분됩니다.

* * 관련 NVMe 네임스페이스 *
+
하위 시스템과 연결된 NVM 네임스페이스의 수를 표시합니다. 숫자 위로 마우스를 가져가면 연결된 네임스페이스 경로가 표시됩니다. 경로를 클릭하여 Namespace Details 창을 표시합니다.





== 도구 모음

도구 모음은 열 머리글 위에 있습니다. 도구 모음의 필드와 버튼을 사용하여 다양한 작업을 수행할 수 있습니다.

* * 검색 *
+
이름 * 열에 있는 값을 검색할 수 있습니다.

* * 필터링 *
+
목록을 필터링하는 다양한 방법이 나열된 드롭다운 메뉴에서 선택할 수 있습니다.

* * 생성 *
+
NVMe 하위 시스템을 생성할 수 있는 NVMe 하위 시스템 생성 대화 상자를 엽니다.

* * 편집 *
+
기존 NVMe 하위 시스템을 편집할 수 있는 Edit NVMe Subsystem(NVMe 하위 시스템 편집) 대화 상자를 엽니다.

* * 삭제 *
+
기존 NVMe 하위 시스템을 삭제할 수 있는 NVMe 하위 시스템 삭제 확인 대화 상자를 엽니다.


