---
permalink: online-help-96-97/reference_nvme_namespaces_window.html 
sidebar: sidebar 
keywords: nvme, namespace, command, button, subsystems, protocol, online, help 
summary: NVMe Namepaces 창을 사용하여 NVMe 프로토콜에 대한 네임스페이스 및 관련 하위 시스템을 설정하고 관리할 수 있습니다. 네임스페이스 경로를 사용하여 기존 네임스페이스를 검색할 수 있습니다. 
---
= NVMe 네임스페이스 창
:icons: font
:imagesdir: ../media/


[role="lead"]
NVMe Namepaces 창을 사용하여 NVMe 프로토콜에 대한 네임스페이스 및 관련 하위 시스템을 설정하고 관리할 수 있습니다. 네임스페이스 경로를 사용하여 기존 네임스페이스를 검색할 수 있습니다.



== 명령 버튼

* * 생성 *
+
새 네임스페이스를 설정하고 NVMe 하위 시스템에 매핑할 수 있는 NVMe 네임스페이스 만들기 대화 상자를 엽니다.

* * 편집 *
+
네임스페이스 매핑을 편집할 수 있습니다.

* * 삭제 *
+
선택한 네임스페이스를 삭제합니다.

* * 추가 작업 *
+
기존 서브시스템과 연결할 수 있는 선택한 네임스페이스의 클론을 만들거나 이를 하위 시스템에 매핑하지 않도록 선택할 수 있습니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





== NVMe 목록

* * 상태 *
+
네임스페이스가 온라인 또는 오프라인인 경우에 표시됩니다.

* * 네임스페이스 경로 *
+
'/vol/volume'/file' 형식의 새 네임스페이스 경로입니다. 네임스페이스 경로는 클릭할 수 있는 링크입니다. 링크를 클릭하면 네임스페이스 세부 정보 페이지로 이동합니다.

* * NVMe 하위 시스템 *
+
네임스페이스에 연결된 하위 시스템의 이름입니다. 서브시스템이 연결되어 있지 않으면 이 열의 값이 없음 으로 표시됩니다. NVMe 하위 시스템에 대해 이 열을 필터링하면 매핑되지 않은 네임스페이스 목록을 볼 수 있습니다.

* SVM *
+
네임스페이스가 생성되는 SVM 이름입니다. SVM 이름은 클릭 가능한 링크입니다. 링크를 클릭하면 기존 SVM 대시보드 페이지로 이동합니다.

+
ONTAP 9.5부터 SVM과 연결된 HA 쌍의 각 노드에 대해 하나 이상의 NVMe LIF를 구성해야 합니다. 페어의 각 노드에 대해 최대 2개의 NVMe LIF를 생성할 수 있습니다.

* * 네임스페이스 ID *
+
이름 공간에 대한 액세스를 제공하기 위해 컨트롤러에서 사용하는 고유 식별자입니다. 이는 사용자 입력이 아니며 새 네임스페이스가 생성될 때 시스템에서 생성됩니다.

* * 총 공간 *
+
네임스페이스의 총 크기를 표시합니다.

* * 사용된 공간 *
+
네임스페이스에서 사용된 공간의 양을 표시합니다.

* * % 사용 *
+
네임스페이스에서 사용되는 공간 크기(백분율)를 표시합니다. 이 필드의 값은 전체 및 사용된 공간을 사용하여 계산됩니다.





== 세부 정보 영역

선택한 네임스페이스에 대한 정보를 보려면 네임스페이스를 선택할 수 있습니다. 이 영역에서 네임스페이스를 편집, 삭제 또는 클론 복제할 수도 있습니다.

* *** 개요 * 탭**
+
선택한 네임스페이스에 대한 일반 정보를 표시하고 네임스페이스의 공간 할당 및 성능 그림을 표시합니다.

+
개요 탭에서 SVM 및 볼륨 이름을 클릭할 수 있는 링크가 있습니다. 링크를 클릭하면 SVM 및 볼륨 페이지로 각각 이동합니다. 호스트 수는 하나 이상이 될 수 있으며 기본적으로 두 개의 호스트 이름이 표시됩니다. 두 개 이상의 호스트 이름이 표시되면 링크를 클릭하여 추가 호스트에 액세스할 수 있습니다.

+
개요 탭에는 이름 공간의 총 및 사용된 공간 세부 정보를 보여 주는 공간 차트와 지연 시간, IOPS 및 처리량과 같은 세부 정보를 보여 주는 성능 차트도 표시됩니다.

* * 상태 *
+
네임스페이스 상태입니다. 값은 온라인 또는 오프라인일 수 있습니다.

* * 호스트 NQN *
+
호스트 NVMe 정규화된 이름(NQN)은 식별 및 인증을 위해 호스트를 고유하게 설명합니다. 이 필드에는 쉼표로 구분된 NVMe 자격 이름(NQN) 값을 사용할 수 있습니다. 호스트 NQN은 "nqn"으로 시작하고 나머지 검증은 IQN(이니시에이터 자격 평가 이름)과 동일합니다.

* * 호스트 OS *
+
이름 공간에 대한 호스트 운영 체제: Hyper-V, Linux, VMware, Windows 또는 Xen.

* * 볼륨 *
+
네임스페이스가 호스팅되는 볼륨 이름을 표시합니다.

* * 읽기 전용 *
+
네임스페이스가 읽기 전용인지 여부를 표시합니다.

* * 노드 *
+
네임스페이스를 소유하는 노드입니다.

* * 블록 크기 *
+
스토리지 블록의 크기입니다.

* * 액세스할 수 없는 * 복원
+
하위 시스템의 매핑 해제에 실패하고 부분 데이터가 남아 있으면 매핑되지 않은 네임스페이스를 복원할 수 없습니다.


