---
permalink: online-help-96-97/reference_svm_relationships_window.html 
sidebar: sidebar 
keywords: svm, relationship, window, command, button, online, help, mirror 
summary: SVM 관계 창을 사용하여 미러 관계를 생성 및 관리하고 SVM 간 관계를 미러링 및 소산 할 수 있습니다. 
---
= SVM 관계 창
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM 관계 창을 사용하여 미러 관계를 생성 및 관리하고 SVM 간 관계를 미러링 및 소산 할 수 있습니다.



== 명령 버튼

* * 생성 *
+
미러 관계를 생성하거나 타겟 볼륨에서 미러 및 소산 관계를 생성하는 데 사용할 수 있는 SVM 재해 복구 페이지를 엽니다.

* * 편집 *
+
관계의 일정 및 정책을 편집할 수 있습니다.

+
미러 및 볼트 관계 또는 버전에 상관없이 유연한 미러 관계의 경우 정책 유형을 수정하여 관계 유형을 수정할 수 있습니다.

* * 삭제 *
+
관계를 삭제할 수 있습니다.

* * 운영 *
+
에서는 다음 옵션을 제공합니다.

+
** * 초기화 *
+
SVM 관계를 초기화하여 소스 SVM에서 타겟 SVM으로 기본 전송을 수행할 수 있습니다.

** * 업데이트 *
+
소스 SVM에서 타겟 SVM으로 데이터를 업데이트할 수 있습니다.

** * 대상 SVM 활성화 *
+
대상 SVM을 활성화할 수 있습니다.

** * 소스 SVM에서 재동기화 * 를 참조하십시오
+
끊어진 관계의 재동기화를 시작할 수 있습니다.

** * 대상 SVM에서 재동기화(역재동기화) *
+
대상 SVM에서 소스 SVM으로 관계를 재동기화할 수 있습니다.

** * 소스 SVM 재활성화 *
+
소스 SVM을 다시 활성화할 수 있습니다.



* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





== SVM 관계 목록

* * 소스 스토리지 가상 머신 *
+
데이터가 미러링되고 관계를 유지하는 볼륨이 포함된 SVM을 표시합니다.

* * 대상 스토리지 가상 머신 *
+
데이터가 미러링되고 관계를 저장되어 있는 볼륨을 포함하는 SVM을 표시합니다.

* * 은(는) 건강합니다 *
+
관계가 정상 상태인지 여부를 표시합니다.

* * 관계 상태 *
+
SnapMirrored, Uninitialized 또는 Broken Off와 같은 관계 상태를 표시합니다.

* * 전송 상태 *
+
관계 상태를 표시합니다.

* * 관계 유형 *
+
대칭 복사, 대칭 복사, 볼트와 같은 관계 유형을 표시합니다.

* * 지연 시간 *
+
지연 시간은 현재 시간과 타겟 시스템으로 성공적으로 전송된 마지막 스냅샷 복사본의 타임 스탬프의 차이입니다. 지연 시간은 소스 및 대상 시스템의 시계가 동기화되지 않는 한 항상 마지막으로 성공한 전송 기간보다 훨씬 오래 지속됩니다. 시간대 차이는 지연 시간으로 자동 계산됩니다.

* * 정책 이름 *
+
관계에 할당된 정책의 이름을 표시합니다.

* * 정책 유형 *
+
관계에 할당된 정책 유형을 표시합니다. 정책 유형은 StrictSync, Sync, Asynchronous Mirror, Asynchronous Vault 또는 Asynchronous Mirror Vault가 될 수 있습니다.





== 세부 정보 영역

* * 세부 정보 탭 *
+
소스 클러스터 및 타겟 클러스터, SVM과 관련된 보호 관계, 데이터 전송 속도, 관계 상태, 네트워크 압축률에 대한 세부 정보, 데이터 전송 상태, 현재 데이터 전송 유형, 마지막 데이터 전송 유형 등 선택한 관계에 대한 일반 정보를 표시합니다. 최신 스냅샷 복사본, 최신 스냅샷 복사본의 타임스탬프, ID 보호 상태 및 보호된 볼륨 수입니다.

* * 정책 세부 정보 탭 *
+
선택한 보호 관계에 할당된 정책에 대한 세부 정보를 표시합니다.


