---
permalink: online-help-96-97/reference_storage_pools_window.html 
sidebar: sidebar 
keywords: storage, pools, window, online, help, command, button 
summary: 스토리지 풀 창을 사용하여 스토리지 풀이라고도 하는 SSD 전용 캐시를 생성, 표시 및 관리할 수 있습니다. 이러한 스토리지 풀은 비루트 애그리게이트와 연결되어 SSD 캐시를 제공하고 Flash Pool 애그리게이트로 크기를 늘릴 수 있습니다. 
---
= Storage Pools 창
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 풀 창을 사용하여 _스토리지 풀_라고도 하는 SSD 전용 캐시를 생성, 표시 및 관리할 수 있습니다. 이러한 스토리지 풀은 비루트 애그리게이트와 연결되어 SSD 캐시를 제공하고 Flash Pool 애그리게이트로 크기를 늘릴 수 있습니다.

All-Flash 최적화 속성을 가진 노드가 포함된 클러스터에서는 이 페이지를 사용할 수 없습니다.



== 명령 버튼

* * 생성 *
+
스토리지 풀 생성 대화 상자를 엽니다. 이 대화 상자에서 스토리지 풀을 생성할 수 있습니다.

* * 디스크 추가 *
+
스토리지 풀에 캐시 디스크를 추가할 수 있는 디스크 추가 대화 상자를 엽니다.

* * 삭제 *
+
선택한 스토리지 풀을 삭제합니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





== 스토리지 풀 목록입니다

* * 이름 *
+
스토리지 풀의 이름을 표시합니다.

* * 총 캐시 *
+
스토리지 풀의 총 캐시 크기를 표시합니다.

* * 스페어 캐시 *
+
스토리지 풀의 사용 가능한 스페어 캐시 크기를 표시합니다.

* * 사용된 캐시(%) *
+
스토리지 풀의 사용된 캐시 크기 비율을 표시합니다.

* * 할당 단위 *
+
스토리지 풀의 크기를 늘리는 데 사용할 수 있는 총 캐시 크기의 최소 할당 단위를 표시합니다.

* * 소유자 *
+
스토리지 풀이 연결된 HA 쌍 또는 노드의 이름을 표시합니다.

* * 시/도 *
+
스토리지 풀의 상태가 정상, 성능 저하, 생성, 삭제, 재할당, 있습니다.

* * 은(는) 건강합니다 *
+
스토리지 풀이 정상 상태인지 여부를 표시합니다.





== 세부 정보 탭

선택한 스토리지 풀에 대한 이름, 상태, 스토리지 유형, 디스크 수, 총 캐시, 스페어 캐시, 사용된 캐시 크기(백분율) 및 할당 유닛입니다. 이 탭에는 스토리지 풀이 프로비저닝한 애그리게이트의 이름도 표시됩니다.



== 디스크 탭을 클릭합니다

이름, 디스크 유형, 사용 가능한 크기 및 총 크기와 같이 선택한 스토리지 풀의 디스크에 대한 세부 정보를 표시합니다.

* 관련 정보 *

xref:task_adding_disks_to_storage_pool.adoc[스토리지 풀에 디스크 추가]

xref:task_creating_storage_pool.adoc[스토리지 풀을 생성하는 중입니다]

xref:task_deleting_storage_pools.adoc[스토리지 풀을 삭제하는 중입니다]
