---
permalink: online-help-96-97/reference_shares_window.html 
sidebar: sidebar 
keywords: command, buttons, shares, window, online, help 
summary: 공유 창을 사용하여 공유를 관리하고 공유에 대한 정보를 볼 수 있습니다. 
---
= 공유 창
:icons: font
:imagesdir: ../media/


[role="lead"]
공유 창을 사용하여 공유를 관리하고 공유에 대한 정보를 볼 수 있습니다.



== 명령 버튼

* * 공유 생성 *
+
공유를 생성할 수 있는 공유 생성 대화 상자를 엽니다.

* * 홈 디렉토리 생성 *
+
새 홈 디렉토리 공유를 생성할 수 있는 홈 디렉토리 공유 생성 대화 상자를 엽니다.

* * 편집 *
+
선택한 공유의 속성을 수정할 수 있는 설정 편집 대화 상자를 엽니다.

* * 공유 중지 *
+
선택한 개체를 공유하지 않습니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





== 공유 목록

공유 목록에는 각 공유의 이름과 경로가 표시됩니다.

* * 공유 이름 *
+
공유 이름을 표시합니다.

* * 경로 *
+
공유된 기존 폴더, qtree 또는 볼륨의 전체 경로 이름을 표시합니다. 경로 구분 기호는 역슬래시 또는 슬래시일 수 있지만 ONTAP는 모든 경로 구분 기호를 슬래시 로 표시합니다.

* * 홈 디렉토리 *
+
홈 디렉토리 공유의 이름을 표시합니다.

* * 설명 *
+
공유에 대한 추가 설명을 표시합니다(있는 경우).

* * 지속적으로 사용 가능한 공유 *
+
지속적인 가용성을 위해 공유가 설정되었는지 여부를 표시합니다. System Manager 9.6부터 FlexGroup 볼륨의 지속적인 가용성이 지원됩니다.





== 세부 정보 영역

공유 목록 아래의 영역에는 각 공유에 대한 공유 속성 및 액세스 권한이 표시됩니다.

* * 속성 *
+
** 이름
+
공유 이름을 표시합니다.

** oplocks 상태입니다
+
공유가 임시 잠금(oplocks)을 사용하는지 여부를 지정합니다.

** 검색 가능
+
Windows 클라이언트가 공유를 검색할 수 있는지 여부를 지정합니다.

** 스냅샷 표시
+
클라이언트에서 스냅샷 복사본을 볼 수 있는지 여부를 지정합니다.

** 지속적으로 사용 가능한 공유
+
지속적인 가용성을 위해 공유를 설정하거나 해제할지 여부를 지정합니다. System Manager 9.6부터 FlexGroup 볼륨의 지속적인 가용성이 지원됩니다.

** 액세스 기반 열거
+
공유에 대해 ABE(액세스 기반 열거)를 사용할지 여부를 지정합니다.

** BranchCache입니다
+
공유에서 BranchCache를 설정 또는 해제할지 여부를 지정합니다.

** SMB 암호화
+
SMB 3.0을 사용한 데이터 암호화가 SVM(스토리지 가상 머신) 레벨에서 활성화되는지 공유 레벨에서 활성화되는지를 지정합니다. SVM 레벨에서 SMB 암호화가 활성화된 경우 SMB 암호화는 모든 공유에 적용되며 값이 SVM 레벨에서 Enabled로 표시됩니다.

** 이전 버전
+
클라이언트에서 이전 버전을 보고 복원할 수 있는지 여부를 지정합니다.



* * 공유 액세스 제어 *
+
공유에 대한 도메인 사용자, 도메인 그룹, 로컬 사용자 및 로컬 그룹의 액세스 권한을 표시합니다.



* 관련 정보 *

xref:task_creating_cifs_share.adoc[CIFS 공유를 생성하는 중입니다]

xref:task_stopping_share_access.adoc[공유 액세스를 중지하는 중입니다]

xref:task_editing_share_settings.adoc[공유 설정 편집]
