---
permalink: online-help-96-97/reference_windows_window.html 
sidebar: sidebar 
keywords: storage, virtual, machine, svm, cluster, online, help, user, tab, command, buttons, group 
summary: 'Windows 창을 사용하여 클러스터의 각 SVM(스토리지 가상 머신)에 대한 로컬 Windows 사용자 및 그룹 목록을 유지할 수 있습니다. 로컬 Windows 사용자 및 그룹을 인증 및 이름 매핑에 사용할 수 있습니다.' 
---
= Windows 창
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows 창을 사용하여 클러스터의 각 SVM(스토리지 가상 머신)에 대한 로컬 Windows 사용자 및 그룹 목록을 유지할 수 있습니다. 로컬 Windows 사용자 및 그룹을 인증 및 이름 매핑에 사용할 수 있습니다.



== 사용자 탭

사용자 탭을 사용하여 SVM에 대한 로컬 Windows 사용자를 볼 수 있습니다.



== 명령 버튼

* * 생성 *
+
SMB 연결을 통해 SVM에 포함된 데이터에 대한 액세스를 승인하는 데 사용할 수 있는 로컬 Windows 사용자 계정을 생성할 수 있는 사용자 생성 대화 상자를 엽니다.

* * 편집 *
+
사용자 편집 대화 상자를 엽니다. 이 대화 상자에서 그룹 구성원 자격 및 전체 이름과 같은 로컬 Windows 사용자 속성을 편집할 수 있습니다. 사용자 계정을 활성화하거나 비활성화할 수도 있습니다.

* * 삭제 *
+
더 이상 필요하지 않은 경우 SVM에서 로컬 Windows 사용자 계정을 삭제할 수 있는 사용자 삭제 대화 상자를 엽니다.

* * 그룹에 추가 *
+
사용자에게 해당 그룹과 관련된 권한을 부여하려면 사용자 계정에 그룹 구성원을 할당할 수 있는 그룹 추가 대화 상자를 엽니다.

* * 암호 설정 *
+
Windows 로컬 사용자의 암호를 재설정할 수 있는 암호 재설정 대화 상자를 엽니다. 예를 들어, 암호가 손상되었거나 사용자가 암호를 잊어버린 경우 암호를 재설정할 수 있습니다.

* * 이름 바꾸기 *
+
로컬 Windows 사용자 계정의 이름을 보다 쉽게 식별할 수 있도록 사용자 이름 바꾸기 대화 상자를 엽니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





== 사용자 목록

* * 이름 *
+
로컬 사용자의 이름을 표시합니다.

* * 전체 이름 *
+
로컬 사용자의 전체 이름을 표시합니다.

* * 계정이 비활성화됨 *
+
로컬 사용자 계정의 사용 여부를 표시합니다.

* * 설명 *
+
이 로컬 사용자에 대한 설명을 표시합니다.





== 사용자 세부 정보 영역

* * 그룹 *
+
사용자가 구성원인 그룹의 목록을 표시합니다.





== 그룹 탭

그룹 탭을 사용하여 SVM에 로컬 있는 Windows 그룹을 추가, 편집 또는 삭제할 수 있습니다.



== 명령 버튼

* * 생성 *
+
SMB 연결을 통해 SVM에 포함된 데이터에 대한 액세스 권한을 부여하는 데 사용할 수 있는 로컬 Windows 그룹을 생성할 수 있는 그룹 생성 대화 상자를 엽니다.

* * 편집 *
+
그룹에 할당된 권한 및 그룹 설명과 같은 로컬 Windows 그룹 속성을 편집할 수 있는 그룹 편집 대화 상자를 엽니다.

* * 삭제 *
+
더 이상 필요하지 않은 경우 SVM에서 로컬 Windows 그룹을 삭제할 수 있는 그룹 삭제 대화 상자를 엽니다.

* * 구성원 추가 *
+
로컬 또는 Active Directory 사용자 또는 Active Directory 그룹을 로컬 Windows 그룹에 추가할 수 있는 구성원 추가 대화 상자를 엽니다.

* * 이름 바꾸기 *
+
로컬 Windows 그룹의 이름을 보다 쉽게 식별할 수 있도록 그룹 이름 바꾸기 대화 상자를 엽니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





== 그룹 목록

* * 이름 *
+
로컬 그룹의 이름을 표시합니다.

* * 설명 *
+
이 로컬 그룹에 대한 설명을 표시합니다.





== 그룹 세부 정보 영역

* * 권한 *
+
선택한 그룹과 연결된 권한 목록을 표시합니다.

* 사용자 *
+
선택한 그룹과 연결된 로컬 사용자 목록을 표시합니다.



* 관련 정보 *

xref:task_creating_local_user_group.adoc[로컬 Windows 그룹 생성]

xref:task_editing_local_windows_group_properties.adoc[로컬 Windows 그룹 속성 편집]

xref:task_adding_user_accounts_to_windows_local_group.adoc[Windows 로컬 그룹에 사용자 계정 추가]

xref:task_renaming_local_windows_group.adoc[로컬 Windows 그룹의 이름을 바꿉니다]

xref:task_deleting_local_windows_group.adoc[로컬 Windows 그룹을 삭제하는 중입니다]

xref:task_creating_local_windows_user_accounts.adoc[로컬 Windows 사용자 계정 생성]

xref:task_editing_local_windows_user_properties.adoc[로컬 Windows 사용자 속성 편집]

xref:task_assigning_group_memberships_to_user_account.adoc[사용자 계정에 그룹 구성원 자격 할당]

xref:task_renaming_local_windows_user.adoc[로컬 Windows 사용자 이름 바꾸기]

xref:task_changing_password_for_windows_local_users.adoc[Windows 로컬 사용자의 암호 재설정]

xref:task_deleting_local_windows_user_account.adoc[로컬 Windows 사용자 계정을 삭제하는 중입니다]
