---
permalink: online-help-96-97/task_adding_licenses.html 
sidebar: sidebar 
keywords: system, manager, add, license, storage, software, online, help 
summary: 스토리지 시스템 소프트웨어가 출하 시 설치된 경우 System Manager는 자동으로 라이센스 목록에 소프트웨어를 추가합니다. 소프트웨어가 출하 시 설치되지 않았거나 추가 소프트웨어 라이센스를 추가하려는 경우 System Manager를 사용하여 소프트웨어 라이센스를 추가할 수 있습니다. 
---
= System Manager로 라이센스 추가 - ONTAP 9.7 이하
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
출하 시 소프트웨어가 설치되지 않았거나 추가 소프트웨어 라이센스를 추가하려는 경우 ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하여 소프트웨어 라이센스를 추가할 수 있습니다.

스토리지 시스템 소프트웨어가 출하 시 설치된 경우 System Manager는 자동으로 라이센스 목록에 소프트웨어를 추가합니다.

특정 ONTAP 서비스에 대한 소프트웨어 라이센스 코드를 사용할 수 있어야 합니다.

.이 작업에 대해
* MetroCluster 구성에서 새 라이센스를 추가하는 경우 나머지 사이트 클러스터에도 라이센스를 추가하는 것이 좋습니다.
* 시스템 관리자를 사용하여 Cloud Volumes ONTAP 라이센스를 추가할 수는 없습니다.
+
Cloud Volumes ONTAP 라이센스가 라이센스 페이지에 나열되지 않습니다. System Manager에서는 Cloud Volumes ONTAP 라이센스의 자격 위험 상태에 대한 경고를 표시하지 않습니다.

* 용량 기반 라이센스만 업로드할 수 있습니다.
+
용량 기반 라이센스는 "json" 유형입니다.



.단계
. 구성 * > * 클러스터 * > * 라이센스 * 를 클릭합니다.
. 추가 * 를 클릭합니다.
. 라이센스 추가 * 대화 상자에서 적절한 단계를 수행합니다.
+
|===
| 원하는 작업 | 수행할 작업... 


 a| 
특정 ONTAP 서비스에 대한 라이센스를 추가합니다
 a| 
.. 소프트웨어 라이센스 키를 입력합니다.
+
소프트웨어 라이센스 키를 쉼표로 구분하여 입력하여 여러 라이센스를 추가할 수 있습니다.

.. 추가 * 를 클릭합니다.




 a| 
용량 기반 라이센스를 추가합니다
 a| 
.. 찾아보기 를 클릭한 다음 용량 기반 라이센스 파일을 선택합니다.
.. 추가 * 를 클릭합니다.




 a| 
특정 ONTAP 서비스에 대한 라이센스를 추가하고 용량 기반 라이센스를 추가합니다
 a| 
.. 소프트웨어 라이센스 키를 입력합니다.
+
소프트웨어 라이센스 키를 쉼표로 구분하여 입력하여 여러 라이센스를 추가할 수 있습니다.

.. 찾아보기 를 클릭한 다음 용량 기반 라이센스 파일을 선택합니다.
.. 추가 * 를 클릭합니다.


|===
+
새 라이센스가 추가됩니다.

+
Add License Status 대화 상자에 성공적으로 추가된 라이센스 목록이 표시됩니다. 이 대화 상자에는 추가되지 않은 라이센스의 라이센스 키와 라이센스가 추가되지 않은 이유도 표시됩니다.

. 닫기 * 를 클릭합니다.


소프트웨어 라이센스가 스토리지 시스템에 추가되고 라이센스 창의 라이센스 목록에 표시됩니다.

* 관련 정보 *

xref:reference_licenses_window.adoc[라이센스 창]
