---
permalink: online-help-96-97/task_creating_svm_peers.html 
sidebar: sidebar 
keywords: create, svm, peers, relationship, data, protection, online, help 
summary: 'SVM 피어링을 통해 두 SVM(스토리지 가상 시스템) 간에 피어 관계를 설정하여 데이터 보호를 제공할 수 있습니다.' 
---
= SVM 피어 생성
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM 피어링을 통해 두 SVM(스토리지 가상 시스템) 간에 피어 관계를 설정하여 데이터 보호를 제공할 수 있습니다.

피어로 사용하려는 SVM이 상주하는 클러스터 간에 피어 관계를 생성해야 합니다.

.이 작업에 대해
* SVM 피어를 생성할 때 * 구성 * > * SVM 피어 * 창을 사용하여 타겟 클러스터로 선택할 수 있는 클러스터가 나열됩니다.
* ONTAP 9.2 이하를 실행하는 시스템에서 타겟 SVM이 클러스터에 상주하는 경우 System Manager를 사용하여 SVM 피어링을 수락할 수 없습니다.
+
[NOTE]
====
이러한 경우 CLI(Command-Line Interface)를 사용하여 SVM 피어링을 허용할 수 있습니다.

====


.단계
. 이니시에이터 SVM을 선택합니다.
. 허용된 SVM 목록에서 타겟 SVM을 선택합니다.
. SVM * 입력 필드에서 타겟 SVM의 이름을 지정합니다.
+
[NOTE]
====
Configuration * > * SVM 피어 * 창에서 탐색한 경우 피어링된 클러스터 목록에서 타겟 SVM을 선택해야 합니다.

====
. SVM 피어링을 시작합니다.
+
|===
| 원하는 작업 | 수행할 작업... 


 a| 
이니시에이터 클러스터에서 SVM 피어링을 시작합니다
 a| 
SVM 피어링 시작 을 클릭합니다.



 a| 
원격 클러스터에서 SVM 피어링을 수락합니다
 a| 
[NOTE]
====
허용되지 않는 SVM에 적용됩니다

====
.. 원격 클러스터의 관리 주소를 지정합니다.
.. 원격 클러스터의 SVM 피어 창에 액세스하려면 * 관리 URL * 링크를 클릭하십시오.
.. 원격 클러스터에서 * Pending SVM Peer * 요청을 수락합니다.
.. 이니시에이터 클러스터에 액세스한 다음 * 피어링 검증 * 을 클릭합니다.


|===
. 계속 * 을 클릭합니다.




== 다음 단계

요약 창에서 인터클러스터 LIF, 클러스터 피어 관계 및 SVM 피어 관계를 볼 수 있습니다.

System Manager를 사용하여 피어 관계를 만들면 기본적으로 암호화 상태가 ""활성화됨""으로 설정됩니다.
