---
permalink: online-help-96-97/task_creating_local_windows_user_accounts.html 
sidebar: sidebar 
keywords: create, local, windows, user, account, online, help, system, manager, svm, cifs 
summary: 'System Manager를 사용하면 SMB 연결을 통해 SVM(스토리지 가상 시스템)에 포함된 데이터에 대한 액세스를 승인하는 데 사용할 수 있는 로컬 Windows 사용자 계정을 만들 수 있습니다. CIFS 세션을 생성할 때 인증에 로컬 Windows 사용자 계정을 사용할 수도 있습니다.' 
---
= 로컬 Windows 사용자 계정을 만듭니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager를 사용하면 SMB 연결을 통해 SVM(스토리지 가상 시스템)에 포함된 데이터에 대한 액세스를 승인하는 데 사용할 수 있는 로컬 Windows 사용자 계정을 만들 수 있습니다. CIFS 세션을 생성할 때 인증에 로컬 Windows 사용자 계정을 사용할 수도 있습니다.

.시작하기 전에
* SVM용으로 CIFS 서버를 구성해야 합니다.


로컬 Windows 사용자 이름은 다음 요구 사항을 충족해야 합니다.

* 20자를 초과할 수 없습니다
* 마침표로 끝나서는 안 됩니다
* 쉼표를 포함해서는 안 됩니다
* 다음 인쇄 가능한 문자를 포함해서는 안 됩니다."/\[]:|<>+=;? *@
* 인쇄할 수 없는 ASCII 범위 1에서 31 사이의 문자를 포함해서는 안 됩니다


암호는 다음 기준을 충족해야 합니다.

* 6자 이상이어야 합니다
* 사용자 계정 이름을 포함해서는 안 됩니다
* 다음 4개 범주 중 3개 이상의 문자를 포함해야 합니다.
+
** 영어 대문자(A ~ Z)
** 영어 소문자(a ~ z)
** 기본 10자리(0 ~ 9)
** 특수 문자:~! @#0^& *_-+="\|()[]:;"<>,. ? /




.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 호스트 사용자 및 그룹 * 창에서 * Windows * 를 클릭합니다.
. 사용자 * 탭에서 * 생성 * 을 클릭합니다.
. 로컬 사용자의 이름을 지정합니다.
. 로컬 사용자의 전체 이름과 이 새 사용자를 식별하는 데 도움이 되는 설명을 지정합니다.
. 로컬 사용자의 암호를 입력하고 암호를 확인합니다.
+
암호는 암호 요구 사항을 충족해야 합니다.

. Add * (추가 *)를 클릭하여 그룹 멤버쉽을 사용자에게 할당합니다.
. Add Groups * 창의 SVM에서 사용 가능한 그룹 목록에서 그룹을 선택합니다.
. 사용자가 생성된 후 이 계정을 비활성화하려면 * 이 계정 비활성화 * 를 선택합니다.
. Create * 를 클릭합니다.


로컬 Windows 사용자 계정이 생성되고 선택한 그룹에 구성원이 할당됩니다. 사용자 계정이 * Users * 탭에 나열됩니다.

* 관련 정보 *

xref:reference_windows_window.adoc[Windows 창]
