---
permalink: online-help-96-97/task_provisioning_storage_by_creating_flash_pool_aggregate_manually.html 
sidebar: sidebar 
keywords: provision, system, manager, storage, create, flash, pool, aggregate, manually, online, help, hdd 
summary: System Manager를 사용하면 Flash Pool 애그리게이트를 수동으로 생성하거나, SSD를 추가하여 기존 HDD 애그리게이트를 Flash Pool 애그리게이트로 전환할 수 있습니다. 새 HDD 애그리게이트를 생성할 경우, SSD 캐시를 프로비저닝하고 Flash Pool 애그리게이트를 생성할 수 있습니다. 
---
= System Manager-ONTAP 9.7 이하를 사용하여 스토리지를 프로비저닝하고 Flash Pool 애그리게이트를 수동으로 생성합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 Flash Pool 애그리게이트를 수동으로 생성하거나, SSD를 추가하여 기존 HDD 애그리게이트를 Flash Pool 애그리게이트로 전환할 수 있습니다. 새 HDD 애그리게이트를 생성할 경우, SSD 캐시를 프로비저닝하고 Flash Pool 애그리게이트를 생성할 수 있습니다.

.시작하기 전에
* 플랫폼별 모범 사례와 Flash Pool 애그리게이트 SSD 계층 크기 및 구성에 대한 워크로드별 모범 사례를 알고 있어야 합니다.
* 모든 HDD가 Zeroed 상태여야 합니다.
* 애그리게이트에 SSD를 추가하려면 기존 SSD와 전용 SSD의 크기가 모두 같아야 합니다.


.이 작업에 대해
* Flash Pool 애그리게이트를 생성하는 동안에는 파티셔닝된 SSD를 사용할 수 없습니다.
* 캐시 소스가 스토리지 풀인 경우 애그리게이트를 미러링할 수 없습니다.
* ONTAP 9.0부터는 디스크 크기가 10TB보다 크거나 같은 애그리게이트를 생성할 수 있습니다.
* Aggregate 디스크의 디스크 유형이 FSA 또는 mSATA 이고 디스크 크기가 10TB보다 크거나 같은 경우, RAID-TEC는 RAID 유형에 사용할 수 있는 유일한 옵션입니다.


.단계
. 다음 방법 중 하나를 사용하여 Aggregate를 생성합니다.
+
** Applications & Tiers * > * Storage Tiers * > * Add Aggregate * 를 클릭합니다.
** 스토리지 * > * 집계 및 디스크 * > * 집계 * > * 생성 * 을 클릭합니다.


. Aggregate를 생성하려면 * Manually Create Aggregate * 옵션을 활성화합니다.
. Create Aggregate * 창에서 Aggregate 이름, 디스크 유형 및 Aggregate의 HDD에 포함할 디스크 또는 파티션의 수를 지정합니다.
. Aggregate를 미러링하려면 * Mirror this aggregate * 확인란을 선택합니다.
+
MetroCluster 구성의 경우 미러링되지 않은 애그리게이트 생성이 제한됩니다. 따라서 MetroCluster 구성에서는 미러링 옵션이 기본적으로 활성화됩니다.

. 이 Aggregate와 함께 Flash Pool Cache 사용 * 을 클릭합니다.
. 캐시 소스 지정:
+
|===
| 캐시 소스를 선택하려는 경우... | 그러면... 


 a| 
지원합니다
 a| 
.. 캐시 소스로 * 스토리지 풀 * 을 선택합니다.
.. 캐시를 가져올 수 있는 스토리지 풀을 선택한 다음 캐시 크기를 지정합니다.
.. 필요한 경우 RAID 유형을 수정합니다.




 a| 
전용 SSD
 a| 
.. 캐시 소스로 * 전용 SSD * 를 선택합니다.
.. SSD 크기와 애그리게이트에 포함될 SSD 수를 선택합니다.
.. 필요한 경우 RAID 구성을 수정합니다.
+
... 변경 * 을 클릭합니다.
... RAID 구성 변경 대화 상자에서 RAID 유형과 RAID 그룹 크기를 지정합니다.
... 저장 * 을 클릭합니다.




|===
. Create * 를 클릭합니다.


Flash Pool 애그리게이트는 지정된 구성으로 생성되며 애그리게이트 창의 애그리게이트 목록에 추가됩니다.

* 관련 정보 *

xref:concept_how_storage_pool_works.adoc[스토리지 풀의 작동 방식]

http://www.netapp.com/us/media/tr-4070.pdf["NetApp 기술 보고서 4070: Flash Pool 설계 및 구축"^]
