---
permalink: online-help-96-97/task_creating_storage_pool.html 
sidebar: sidebar 
keywords: create, storage, pool, ssd, cache, disks, online, help, storage, pool 
summary: '스토리지 풀은 SSD(캐시 디스크)의 모음입니다. System Manager를 사용하면 SSD를 결합하여 스토리지 풀을 생성할 수 있습니다. 이 경우 HA 쌍 간에 SSD와 SSD 스페어를 공유하여 동시에 2개 이상의 Flash Pool 애그리게이트에 할당될 수 있습니다.' 
---
= 스토리지 풀을 생성합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 풀은 SSD(캐시 디스크)의 모음입니다. System Manager를 사용하면 SSD를 결합하여 스토리지 풀을 생성할 수 있습니다. 이 경우 HA 쌍 간에 SSD와 SSD 스페어를 공유하여 동시에 2개 이상의 Flash Pool 애그리게이트에 할당될 수 있습니다.

.시작하기 전에
* 스토리지 풀을 통해 SSD와 SSD 스페어를 할당하려면 HA 쌍의 두 노드가 모두 가동 및 실행 중이어야 합니다.
* 스토리지 풀에는 최소 3개의 SSD가 있어야 합니다.
* 스토리지 풀의 모든 SSD는 동일한 HA 쌍이 소유해야 합니다.


System Manager에서는 SSD를 사용하여 스토리지 풀에 디스크를 추가할 때 SSD RAID 그룹에 핫 스페어 규칙을 적용합니다. 예를 들어, SSD RAID 그룹에 10개의 SSD가 있고 노드 레벨에서 RAID.min_spare_count 옵션이 '1'로 설정된 경우 System Manager에서는 1개의 SSD를 핫 스페어로 두고 다른 9개의 SSD를 SSD 관련 작업에 사용합니다.

System Manager를 사용하여 스토리지 풀을 생성할 때는 파티션이 설정된 SSD를 사용할 수 없습니다.

.단계
. 스토리지 * > * 애그리게이트 및 디스크 * > * 스토리지 풀 * 을 클릭합니다.
. Storage Pools * 창에서 * Create * 를 클릭합니다.
. Create Storage Pool * 대화 상자에서 스토리지 풀의 이름, 디스크 크기 및 디스크 수를 지정합니다.
. Create * 를 클릭합니다.


* 관련 정보 *

xref:reference_storage_pools_window.adoc[Storage Pools 창]
