---
permalink: online-help-96-97/task_creating_cluster_peer_relationships.html 
sidebar: sidebar 
keywords: system, manager, create, cluster, peer, relationships, online, help 
summary: 인증된 클러스터 피어 관계를 생성하여 클러스터를 연결하면 피어 관계의 클러스터가 서로 안전하게 통신할 수 있습니다. 
---
= 클러스터 피어 관계 생성
:icons: font
:imagesdir: ../media/


[role="lead"]
인증된 클러스터 피어 관계를 생성하여 클러스터를 연결하면 피어 관계의 클러스터가 서로 안전하게 통신할 수 있습니다.

.시작하기 전에
* 이 작업을 수행하기 위한 요구 사항을 검토하고 완료해야 합니다.
+
link:reference_prerequisites_for_cluster_peering.md#["클러스터 피어링을 위한 사전 요구사항"]

* 인터클러스터 논리 인터페이스(LIF)를 만들어야 합니다.
* 각 클러스터가 실행 중인 ONTAP 버전은 어떤 버전인지 알고 있어야 합니다.


.이 작업에 대해
* Data ONTAP 8.2.2 이하를 실행하는 클러스터와 피어 관계를 생성하려면 CLI를 사용해야 합니다.
* ONTAP 9.5를 실행하는 클러스터와 ONTAP 9.6을 실행하는 클러스터 간에 피어 관계를 생성할 수 있습니다. 그러나 ONTAP 9.5에서는 암호화가 지원되지 않으므로 피어 관계를 암호화할 수 없습니다.
* MetroCluster 구성에서 운영 클러스터와 외부 클러스터 간에 피어 관계를 생성할 때 정상적인 사이트 클러스터와 외부 클러스터 간에 피어 관계도 만드는 것이 좋습니다.
* 사용자 지정 암호를 생성하거나 시스템에서 생성한 암호를 사용하여 클러스터 피어 관계를 인증할 수 있습니다. 그러나 두 클러스터의 암호는 일치해야 합니다.


.단계
. 구성 * > * 고급 클러스터 설정 * 을 클릭합니다.
. Target Cluster Intercluster LIF IP 주소 * 필드에 원격 클러스터의 인터클러스터 LIF의 IP 주소를 입력합니다.
. ONTAP 9.5를 실행하는 클러스터와 ONTAP 9.6을 실행하는 클러스터 간에 피어 관계를 생성 중인 경우 확인란을 선택합니다.
+
피어 관계는 암호화되지 않습니다. 확인란을 선택하지 않으면 피어 관계가 설정되지 않습니다.

. Passphrase * 필드에서 클러스터 피어 관계에 대한 암호를 지정합니다.
+
사용자 지정 암호를 생성할 경우 피어링된 클러스터의 암호를 기준으로 암호를 검증하여 인증된 클러스터 피어 관계를 보장합니다.

+
로컬 클러스터와 원격 클러스터의 이름이 동일하고 사용자 지정 암호를 사용하는 경우 원격 클러스터에 대한 별칭이 생성됩니다.

. 원격 클러스터에서 암호를 생성하려면 원격 클러스터의 관리 IP 주소를 입력합니다.
. 클러스터 피어링을 시작합니다.
+
|===
| 원하는 작업 | 수행할 작업... 


 a| 
이니시에이터 클러스터에서 클러스터 피어링을 시작합니다
 a| 
클러스터 피어링 시작 * 을 클릭합니다.



 a| 
원격 클러스터에서 클러스터 피어링을 시작합니다(사용자 지정 암호를 생성한 경우 해당).
 a| 
.. 원격 클러스터의 관리 IP 주소를 입력합니다.
.. 원격 클러스터에 액세스하려면 * 관리 URL * 링크를 클릭하십시오.
.. 클러스터 피어링 생성 * 을 클릭합니다.
.. 이니시에이터 클러스터의 인터클러스터 LIF IP 주소 및 암호를 지정합니다.
.. 피어링 시작 * 을 클릭합니다.
.. 이니시에이터 클러스터에 액세스한 다음 * 피어링 검증 * 을 클릭합니다.


|===




== 다음 단계

피어링 프로세스를 계속 진행하려면 SVM 피어링 창에서 SVM 세부 정보를 지정해야 합니다.
