---
permalink: online-help-96-97/task_provisioning_storage_by_creating_snaplock_aggregate_manually.html 
sidebar: sidebar 
keywords: system, manager, worm, provision, storage, create, snaplock, aggregate, online, help 
summary: 'System Manager를 사용하여 SnapLock 규정 준수 애그리게이트 또는 SnapLock 엔터프라이즈 애그리게이트를 수동으로 생성할 수 있습니다. 이러한 애그리게이트에서 SnapLock 볼륨을 생성하여 "WORM(Write Once, Read Many)" 기능을 제공할 수 있습니다.' 
---
= System Manager-ONTAP 9.7 이하를 사용하여 SnapLock 애그리게이트를 수동으로 생성합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 SnapLock 규정 준수 애그리게이트 또는 SnapLock 엔터프라이즈 애그리게이트를 수동으로 생성할 수 있습니다. 이러한 애그리게이트에는 ""WORM(Write Once, Read Many)" 기능을 제공하는 SnapLock 볼륨을 생성할 수 있습니다.

SnapLock 라이센스가 추가되어야 합니다.

.이 작업에 대해
* MetroCluster 구성에서는 SnapLock 엔터프라이즈 애그리게이트만 생성할 수 있습니다.
* 어레이 LUN의 경우 SnapLock 엔터프라이즈 애그리게이트만 지원됩니다.
* ONTAP 9.0부터는 디스크 크기가 10TB보다 크거나 같은 애그리게이트를 생성할 수 있습니다.
* Aggregate 디스크의 디스크 유형이 FSA 또는 mSATA 이고 디스크 크기가 10TB보다 크거나 같은 경우, RAID-TEC는 RAID 유형에 사용할 수 있는 유일한 옵션입니다.
* ONTAP 9.1부터 AFF 플랫폼에 SnapLock 애그리게이트를 만들 수 있습니다.


.단계
. 다음 방법 중 하나를 사용하여 SnapLock Aggregate를 만듭니다.
+
** Applications & Tiers * > * Storage Tiers * > * Add Aggregate * 를 클릭합니다.
** 스토리지 * > * 집계 및 디스크 * > * 집계 * > * 생성 * 을 클릭합니다.


. Aggregate를 생성하려면 * Manually Create Aggregate * 옵션을 활성화합니다.
. SnapLock 애그리게이트 생성하기:
+
.. Aggregate 이름, 디스크 유형 및 Aggregate에 포함할 디스크 또는 파티션의 수를 지정합니다.
+
Aggregate를 생성한 후에는 SnapLock Compliance Aggregate의 이름을 변경할 수 없습니다.

+
최소 핫 스페어 규칙은 디스크 크기가 가장 큰 디스크 그룹에 적용됩니다.

.. Aggregate의 RAID 구성을 수정합니다.
+
... 변경 * 을 클릭합니다.
... RAID 구성 변경 대화 상자에서 RAID 유형과 RAID 그룹 크기를 지정합니다.
+
공유 디스크는 RAID-DP와 RAID-TEC의 두 가지 RAID 유형을 지원합니다.

... 저장 * 을 클릭합니다.


.. SnapLock 유형을 지정합니다.
.. ComplianceClock 시스템을 초기화하지 않은 경우 * ComplianceClock * 초기화 확인란을 선택합니다.
+
ComplianceClock이 이미 노드에서 초기화된 경우에는 이 옵션이 표시되지 않습니다.

+
[NOTE]
====
현재 시스템 시간이 올바른지 확인해야 합니다. ComplianceClock은 시스템 클록을 기반으로 설정됩니다. ComplianceClock이 설정되면 ComplianceClock을 수정하거나 중지할 수 없습니다.

====
.. Aggregate를 미러링하려면 * Mirror this aggregate * 확인란을 선택합니다.
+
MetroCluster 구성의 경우 미러링되지 않은 애그리게이트 생성이 제한됩니다. 따라서 MetroCluster 구성에서는 미러링 옵션이 기본적으로 활성화됩니다.

+
기본적으로 미러링 옵션은 SnapLock 규정 준수 애그리게이트에 대해 비활성화되어 있습니다.



. Create * 를 클릭합니다.

