---
permalink: online-help-96-97/task_editing_local_windows_group_properties.html 
sidebar: sidebar 
keywords: online, help, edit, local, windows, group, properties, active, directory 
summary: System Manager를 사용하여 로컬 사용자, Active Directory 사용자 또는 Active Directory 그룹을 추가 및 제거하여 로컬 그룹 구성원 자격을 관리할 수 있습니다. 그룹에 할당된 권한과 그룹을 쉽게 식별할 수 있도록 그룹 설명을 수정할 수 있습니다. 
---
= 로컬 Windows 그룹 속성 편집
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager를 사용하여 로컬 사용자, Active Directory 사용자 또는 Active Directory 그룹을 추가 및 제거하여 로컬 그룹 구성원 자격을 관리할 수 있습니다. 그룹에 할당된 권한과 그룹을 쉽게 식별할 수 있도록 그룹 설명을 수정할 수 있습니다.

로컬 Windows 그룹에 구성원을 추가하거나 로컬 Windows 그룹에서 구성원을 제거할 때 다음 사항을 염두에 두어야 합니다.

* special_everyone_group에 사용자를 추가하거나 이 그룹에서 사용자를 제거할 수 없습니다.
* 로컬 Windows 그룹을 다른 로컬 Windows 그룹에 추가할 수 없습니다.


.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 호스트 사용자 및 그룹 * 창에서 * Windows * 를 클릭합니다.
. 그룹 * 탭에서 * 편집 * 을 클릭합니다.
. 그룹의 이름과 새 그룹을 식별할 설명을 지정합니다.
. 그룹에 권한 집합을 할당합니다.
+
사전 정의된 지원되는 권한 집합에서 권한을 선택할 수 있습니다.

. 그룹에 사용자를 추가하려면 * 추가 * 를 클릭합니다.
. Add Members* 창에서 다음 작업 중 하나를 수행합니다.
+
** 특정 로컬 그룹에 추가할 Active Directory 사용자 또는 Active Directory 그룹을 지정합니다.
** SVM(스토리지 가상 시스템)에서 사용 가능한 로컬 사용자 목록에서 사용자를 선택합니다.


. 편집 * 을 클릭합니다.


로컬 Windows 그룹 설정이 수정되고 변경 사항이 * Groups * (그룹 *) 탭에 표시됩니다.

* 관련 정보 *

xref:reference_windows_window.adoc[Windows 창]
