---
permalink: online-help-96-97/task_adding_user_accounts_to_windows_local_group.html 
sidebar: sidebar 
keywords: add, user, accounts, windows, local, group, active, directory, online, help 
summary: 'System Manager를 사용하여 로컬 사용자, Active Directory 사용자 또는 Active Directory 그룹(사용자가 해당 그룹과 연결된 권한을 보유하도록 하려는 경우)을 Windows 로컬 그룹에 추가할 수 있습니다.' 
---
= System Manager - ONTAP 9.7 이하를 사용하여 Windows 로컬 그룹에 사용자 계정을 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 및 이전 버전에서 사용 가능)을 사용하여 로컬 사용자, Active Directory 사용자 또는 Active Directory 그룹을 Windows 로컬 그룹에 추가할 수 있습니다(해당 그룹과 연결된 권한을 사용자에게 부여하려는 경우).

.시작하기 전에
* 그룹에 사용자를 추가하려면 그룹이 있어야 합니다.
* 사용자를 그룹에 추가하려면 사용자가 있어야 합니다.


로컬 Windows 그룹에 구성원을 추가할 때는 다음 사항을 염두에 두어야 합니다.

* special_everyone_group에 사용자를 추가할 수 없습니다.
* 로컬 Windows 그룹을 다른 로컬 Windows 그룹에 추가할 수 없습니다.
* System Manager를 사용하면 사용자 이름에 공백이 포함된 사용자 계정을 추가할 수 없습니다.
+
CLI(Command-Line Interface)를 사용하여 사용자 계정의 이름을 바꾸거나 사용자 계정을 추가할 수 있습니다.



.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 호스트 사용자 및 그룹 * 창에서 * Windows * 를 클릭합니다.
. 그룹 * 탭에서 사용자를 추가할 그룹을 선택한 다음 * 구성원 추가 * 를 클릭합니다.
. Add Members* 창에서 다음 작업 중 하나를 수행합니다.
+
** 특정 로컬 그룹에 추가할 Active Directory 사용자 또는 Active Directory 그룹을 지정합니다.
** SVM(스토리지 가상 시스템)에서 사용 가능한 로컬 사용자 목록에서 사용자를 선택합니다.


. 확인 * 을 클릭합니다.


추가한 사용자가 * Groups * 탭의 Userstab에 나열됩니다.

* 관련 정보 *

xref:reference_windows_window.adoc[Windows 창]
