---
permalink: online-help-96-97/task_creating_local_user_group.html 
sidebar: sidebar 
keywords: create, local, window, group, online, help, system, manager 
summary: 'System Manager를 사용하면 SMB 연결을 통해 SVM(스토리지 가상 머신)에 포함된 데이터에 대한 액세스 권한을 부여하는 데 사용할 수 있는 로컬 Windows 그룹을 생성할 수 있습니다. 관리 작업을 수행할 때 그룹의 구성원이 보유한 사용자 권한 또는 기능을 정의하는 권한도 할당할 수 있습니다.' 
---
= 로컬 Windows 그룹을 만듭니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager를 사용하면 SMB 연결을 통해 SVM(스토리지 가상 머신)에 포함된 데이터에 대한 액세스 권한을 부여하는 데 사용할 수 있는 로컬 Windows 그룹을 생성할 수 있습니다. 관리 작업을 수행할 때 그룹의 구성원이 보유한 사용자 권한 또는 기능을 정의하는 권한도 할당할 수 있습니다.

SVM용으로 CIFS 서버를 구성해야 합니다.

.이 작업에 대해
* 로컬 도메인 이름을 사용하거나 사용하지 않고 그룹 이름을 지정할 수 있습니다.
+
로컬 도메인은 SVM용 CIFS 서버의 이름입니다. 예를 들어 SVM의 CIFS 서버 이름이 "'cifs_server''이고 "'engineering'' 그룹을 생성하려면 그룹 이름으로 "'engineering' 또는 "'cifs_server\engineering' 중 하나를 지정할 수 있습니다.

+
그룹 이름의 일부로 로컬 도메인을 사용할 때는 다음 규칙이 적용됩니다.

+
** 그룹이 적용되는 SVM에 대해 로컬 도메인 이름만 지정할 수 있습니다.
+
예를 들어, 로컬 CIFS 서버 이름이 "'CIFS_server''인 경우 그룹 이름으로 "'CORP_SERVER\group1''을 지정할 수 없습니다.

** 그룹 이름에 ""BUILTIN""을(를) 로컬 도메인으로 사용할 수 없습니다.
+
예를 들어, 이름이 ""BUILTIN\group1""인 그룹을 만들 수 없습니다.

** 그룹 이름에서 Active Directory 도메인을 로컬 도메인으로 사용할 수 없습니다.
+
예를 들어 ""AD_DOM\group1""이라는 그룹을 만들 수 없습니다. 여기서 ""AD_DOM""은 Active Directory 도메인의 이름입니다.



* 이미 존재하는 그룹 이름은 사용할 수 없습니다.
* 지정하는 그룹 이름은 다음 요구 사항을 충족해야 합니다.
+
** 256자를 초과할 수 없습니다
** 마침표로 끝나서는 안 됩니다
** 쉼표를 포함해서는 안 됩니다
** 다음 인쇄 가능한 문자를 포함해서는 안 됩니다."/\[]:|<>+=;? *@
** 인쇄할 수 없는 ASCII 범위 1에서 31 사이의 문자를 포함해서는 안 됩니다




.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 호스트 사용자 및 그룹 * 창에서 * Windows * 를 클릭합니다.
. 그룹 * 탭에서 * 생성 * 을 클릭합니다.
. 그룹 만들기 * 대화 상자에서 그룹의 이름과 새 그룹을 식별하는 데 도움이 되는 설명을 지정합니다.
. 그룹에 권한 집합을 할당합니다.
+
사전 정의된 지원되는 권한 집합에서 권한을 선택할 수 있습니다.

. 그룹에 사용자를 추가하려면 * 추가 * 를 클릭합니다.
. 그룹에 구성원 추가 * 대화 상자에서 다음 작업 중 하나를 수행합니다.
+
** 특정 로컬 그룹에 추가할 Active Directory 사용자 또는 Active Directory 그룹을 지정합니다.
** SVM에서 사용 가능한 로컬 사용자 목록에서 사용자를 선택합니다.
** 확인 * 을 클릭합니다.


. Create * 를 클릭합니다.


로컬 Windows 그룹이 생성되어 그룹 창에 나열됩니다.

* 관련 정보 *

xref:reference_windows_window.adoc[Windows 창]
