---
permalink: online-help-96-97/task_managing_svm_relationships.html 
sidebar: sidebar 
keywords: system, manager, manage, svm, online, help, relationship 
summary: System Manager를 사용하여 SVM 관계 초기화, SVM 관계 업데이트, 대상 SVM 활성화, 소스 SVM에서 데이터 재동기화, 대상 SVM에서 데이터 재동기화, 소스 SVM 재활성화 등 SVM 관계에 대한 다양한 작업을 수행할 수 있습니다. 
---
= SVM 관계 관리
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager를 사용하여 SVM 관계 초기화, SVM 관계 업데이트, 대상 SVM 활성화, 소스 SVM에서 데이터 재동기화, 대상 SVM에서 데이터 재동기화, 소스 SVM 재활성화 등 SVM 관계에 대한 다양한 작업을 수행할 수 있습니다.

.시작하기 전에
* SVM 관계를 초기화하려면 소스 및 타겟 클러스터가 양호한 피어 관계에 있어야 합니다.
* SVM 관계를 업데이트하려면 SVM 관계가 초기화되고 SnapMirrored 상태여야 합니다.
* 소스 SVM을 다시 활성화하려면 대상 SVM에서 데이터 재동기화(역방향 재동기화) 작업을 수행해야 합니다.
* SVM 관계를 생성하면서 소스 SVM 구성을 복제하는 옵션을 선택한 경우 SVM 관계를 활성화하려면 소스 SVM을 중지해야 합니다.
* 소스 클러스터와 대상 클러스터에서 SnapMirror 라이센스가 활성화되어야 합니다.
* 소스 클러스터와 대상 클러스터는 정상 피어 관계에 있어야 합니다.
* 대상 클러스터에 사용 가능한 공간이 있어야 합니다.
* 소스 SVM에는 SVM 피어링을 허용할 수 있어야 합니다.
* SVM 관계를 중단하여 타겟 SVM을 활성화하고, 소스 SVM에서 재동기화하며, 타겟 SVM에서 재동기화(역방향 재동기화)하고, 소스 SVM을 재활성화해야 합니다.
* 소스 SVM을 다시 활성화하려면 SVM 역방향 관계가 존재하고 SnapMirrored 상태여야 합니다.


.단계
. 보호 * > * SVM 관계 * 를 클릭합니다.
. SVM 관계를 선택하고 적절한 조치를 수행합니다.
+
|===
| 원하는 작업 | 다음을 수행합니다. 


 a| 
SVM 관계 초기화
 a| 
.. Operations * > * Initialize * 를 클릭합니다.
+
Initialize(초기화) 대화 상자가 표시됩니다.

.. Initialize * 를 클릭합니다.




 a| 
SVM 관계 업데이트
 a| 
.. 운영 * > * 업데이트 * 를 클릭합니다.
+
업데이트 대화 상자가 표시됩니다.

.. Update * 를 클릭합니다.




 a| 
대상 SVM을 활성화하려면 예약된 SnapMirror 전송을 중지하고, 진행 중인 SnapMirror 전송을 중단하고, SVM 관계를 끊은 다음, 대상 SVM을 시작해야 합니다.
 a| 
.. 운영 * > * 대상 SVM 활성화 * 를 클릭합니다.
+
Activate Destination SVM 대화상자가 표시됩니다.

.. OK를 선택하여 대상 SVM을 활성화하고 관계 * 확인란을 지웁니다.
.. Activate * 를 클릭합니다.




 a| 
소스 SVM에서 데이터 재동기화 재동기화 작업은 SVM 구성의 재기준을 수행합니다. 소스 SVM에서 다시 동기화하여 두 SVM 간에 손상된 관계를 재설정할 수 있습니다. 재동기화가 완료되면 타겟 SVM은 소스 SVM과 동일한 정보를 포함하며 추가 업데이트가 예정되어 있습니다.
 a| 
.. 운영 * > * 소스 SVM에서 재동기화 * 를 클릭합니다.
+
소스 SVM에서 재동기화 대화 상자가 표시됩니다.

.. OK를 선택하여 대상 SVM * 확인란의 최신 데이터를 삭제합니다.
.. 재동기화 * 를 클릭합니다.




 a| 
대상 SVM에서 데이터 재동기화(역방향 재동기화) 대상 SVM에서 재동기화하여 두 SVM 간에 새 관계를 생성할 수 있습니다. 이 작업 중에 타겟 SVM은 소스 SVM과 함께 계속해서 데이터를 서브하면서 타겟 SVM의 구성 및 데이터를 백업합니다.
 a| 
.. 작업 * > * 대상 SVM에서 재동기화(역재동기화) * 를 클릭합니다.
+
대상 SVM에서 재동기화(역재동기화) 대화 상자가 표시됩니다.

.. SVM이 여러 개의 관계가 있는 경우 * This SVM has multiple 관계로 있음, OK to release to other 관계는 여러 개 있음 * 확인란을 선택합니다.
.. OK를 선택하여 소스 SVM * 확인란의 새 데이터를 삭제합니다.
.. 역방향 재동기화 * 를 클릭합니다.




 a| 
소스 SVM을 다시 활성화하면 소스 SVM을 다시 활성화하여 소스 SVM과 타겟 SVM 간의 SVM 관계를 보호하고 다시 생성해야 합니다. SVM 관계를 생성하면서 소스 SVM 구성을 복사하는 옵션을 선택한 경우, 타겟 SVM이 데이터 처리를 중지합니다.
 a| 
.. Operations * > * Reactivate Source SVM * 을 클릭합니다.
+
소스 SVM 재활성화 대화 상자가 표시됩니다.

.. 대상 SVM에 대한 재활성화를 시작하려면 * Initiate Reactivation * 을 클릭합니다.
.. 완료 * 를 클릭합니다.


|===

