---
permalink: online-help-96-97/task_creating_node_management_logical_interface.html 
sidebar: sidebar 
keywords: system, manager, create, node, management, logical, interface, online, help 
summary: 'System Manager를 사용하여 클러스터의 특정 노드를 관리할 수 있는 전용 노드 관리 논리 인터페이스(LIF)를 생성할 수 있습니다. 이 LIF를 사용하여 노드의 시스템 유지보수 활동을 관리할 수 있습니다.' 
---
= 노드 관리 논리 인터페이스를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager를 사용하여 클러스터의 특정 노드를 관리할 수 있는 전용 노드 관리 논리 인터페이스(LIF)를 생성할 수 있습니다. 이 LIF를 사용하여 노드의 시스템 유지보수 활동을 관리할 수 있습니다.

.단계
. 구성 * > * 클러스터 * > * 구성 업데이트 * 를 클릭합니다.
. 노드 * 탭에서 노드 관리 LIF를 생성할 노드를 선택한 다음 * 노드 관리 LIF 생성 * 을 클릭합니다.
. 노드 관리 LIF * 생성 대화 상자에서 노드 관리 LIF의 이름을 지정합니다.
. 노드 관리 LIF에 IP 주소를 할당합니다.
+
|===
| 원하는 작업 | 그러면... 


 a| 
서브넷을 사용하여 IP 주소를 지정합니다
 a| 
.. 서브넷 사용 * 을 선택합니다.
.. 세부 정보 추가 대화 상자에서 IP 주소를 할당할 서브넷을 선택합니다.
+
인터클러스터 LIF의 경우 선택한 IPspace와 연결된 서브넷만 표시됩니다.

.. 특정 IP 주소를 LIF에 할당하려면 * 특정 IP 주소 사용 * 을 선택한 다음 IP 주소를 입력합니다.
+
지정한 IP 주소가 서브넷 범위에 아직 없는 경우 서브넷에 추가됩니다.

.. 확인 * 을 클릭합니다.




 a| 
서브넷을 사용하지 않고 수동으로 IP 주소를 지정합니다
 a| 
.. 서브넷 없이 * 를 선택합니다.
.. 세부 정보 추가 대화 상자에서 다음 단계를 수행합니다.
+
... IP 주소와 네트워크 마스크 또는 접두사를 지정합니다.
... 선택 사항: 게이트웨이를 지정합니다.
... 대상 필드의 기본값을 사용하지 않으려면 새 대상 값을 지정합니다.
+
값을 지정하지 않으면 대상 필드가 IP 주소 패밀리를 기준으로 기본값으로 채워집니다.



+
라우트가 존재하지 않으면 게이트웨이와 목적지를 기반으로 새 루트가 자동으로 생성됩니다.

.. 확인 * 을 클릭합니다.


|===
. Ports details * 영역에서 필요한 포트를 선택합니다.
. Create * 를 클릭합니다.




== 다음 단계

기존 노드 관리 LIF를 삭제하려면 CLI(Command-Line Interface)를 사용해야 합니다.
