---
permalink: online-help-96-97/task_creating_vault_relationship_from_destination_svm.html 
sidebar: sidebar 
keywords: system, manager, create, vault, relationship, destination, svm, online, help 
summary: 'System Manager를 사용하여 대상 SVM(스토리지 가상 머신)에서 볼트 관계를 생성하고 볼트 정책을 할당하여 백업 볼트를 생성할 수 있습니다. 시스템에서 데이터가 손실되거나 손상된 경우 백업 데이터를 백업 볼트 대상에서 복원할 수 있습니다.' 
---
= 대상 SVM에서 볼트 관계를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager를 사용하여 대상 SVM(스토리지 가상 머신)에서 볼트 관계를 생성하고 볼트 정책을 할당하여 백업 볼트를 생성할 수 있습니다. 시스템에서 데이터가 손실되거나 손상된 경우 백업 데이터를 백업 볼트 대상에서 복원할 수 있습니다.

.시작하기 전에
* 소스 클러스터는 ONTAP 8.2.2 이상을 실행해야 합니다.
* 소스 클러스터와 대상 클러스터 모두에서 SnapVault 라이센스 또는 SnapMirror 라이센스를 활성화해야 합니다.
+
[NOTE]
====
일부 플랫폼의 경우 대상 클러스터에 SnapVault 라이센스 또는 SnapMirror 라이센스가 있고 DPO 라이센스가 활성화된 경우 소스 클러스터에 SnapVault 라이센스가 없거나 SnapMirror 라이센스가 활성화되어 있지 않아도 됩니다.

====
* 소스 클러스터와 대상 클러스터는 정상 피어 관계에 있어야 합니다.
* 대상 SVM에 사용 가능한 공간이 있어야 합니다.
* 소스 애그리게이트와 대상 애그리게이트는 64비트 애그리게이트로 이루어져야 합니다.
* 읽기/쓰기(RW) 유형의 소스 볼륨이 있어야 합니다.
* 볼트(XDP) 정책이 있어야 합니다.
+
볼트 정책이 없으면 볼트 정책을 작성하거나 자동으로 할당된 기본 볼트 정책(XDPDefault)을 수락해야 합니다.

* FlexVol 볼륨은 온라인과 읽기/쓰기가 가능해야 합니다.
* SnapLock 집계 유형은 같아야 합니다.
* ONTAP 9.2 이하를 실행하는 클러스터에서 SAML 인증이 활성화된 원격 클러스터로 연결하는 경우 원격 클러스터에서 암호 기반 인증을 활성화해야 합니다.


.이 작업에 대해
* System Manager는 계단식 관계를 지원하지 않습니다.
+
예를 들어, 관계의 대상 볼륨은 다른 관계의 소스 볼륨이 될 수 없습니다.

* MetroCluster 구성에서는 동기화 소스 SVM과 동기화 대상 SVM 간에 볼트 관계를 생성할 수 없습니다.
* MetroCluster 구성에서 동기화 소스 SVM 간에 볼트 관계를 생성할 수 있습니다.
* 동기화 소스 SVM의 볼륨에서 데이터 지원 SVM의 볼륨으로 볼트 관계를 생성할 수 있습니다.
* 데이터 지원 SVM의 볼륨에서 동기화 소스 SVM의 데이터 보호(DP) 볼륨으로 볼트 관계를 생성할 수 있습니다.
* 비 SnapLock(운영) 볼륨과 SnapLock 대상(보조) 볼륨 간의 볼트 관계만 생성할 수 있습니다.
* 한 번에 최대 25개의 볼륨을 보호할 수 있습니다.


.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 관계 * 창에서 * 생성 * 을 클릭합니다.
. SVM * 찾아보기 대화 상자에서 타겟 볼륨의 SVM을 선택합니다.
. [보호 관계 작성] * 대화 상자의 [관계 유형 *] 드롭다운 목록에서 * 볼트 * 를 선택합니다.
. 클러스터, SVM 및 소스 볼륨을 지정합니다.
+
지정된 클러스터에서 ONTAP 9.3 이전 버전의 ONTAP 소프트웨어를 실행 중인 경우 피어링된 SVM만 나열됩니다. 지정된 클러스터에서 ONTAP 9.3 이상이 실행 중인 경우 피어링된 SVM 및 허용된 SVM이 나열됩니다.

. 볼륨 이름 접미사를 입력합니다.
+
대상 볼륨 이름을 생성하기 위해 소스 볼륨 이름에 볼륨 이름 접미사가 추가됩니다.

. SnapLock 볼륨을 생성하는 경우 기본 보존 기간을 지정합니다.
+
기본 보존 기간은 1일 ~ 70년 또는 Infinite 사이의 값으로 설정할 수 있습니다.

. 찾아보기 * 를 클릭한 다음 볼트 정책을 변경합니다.
. 기존 일정 목록에서 관계의 일정을 선택합니다.
. 볼트 관계를 초기화하려면 * 관계 초기화 * 를 선택합니다.
. SnapLock 애그리게이트를 사용하도록 설정한 다음 SnapLock 규정 준수 애그리게이트 또는 SnapLock 엔터프라이즈 애그리게이트를 선택합니다.
. FabricPool 지원 애그리게이트를 사용하도록 설정한 다음 적절한 계층화 정책을 선택합니다.
. 선택한 볼륨에 일치하는 레이블이 있는지 확인하려면 * Validate * 를 클릭합니다.
. Create * 를 클릭합니다.


대상 볼륨을 생성하도록 선택한 경우 다음 기본 설정으로 _DP_ 유형의 볼륨이 생성됩니다.

* 자동 확장 기능이 설정되어 있습니다.
* 사용자 기본 설정 또는 소스 볼륨 중복 제거 설정에 따라 중복 제거가 설정 또는 해제됩니다.
* 압축이 사용되지 않습니다.
* 언어 속성은 소스 볼륨의 언어 특성과 일치하도록 설정됩니다.


대상 볼륨과 소스 볼륨 사이에 볼트 관계가 생성됩니다. 관계를 초기화하기로 선택한 경우 기본 스냅샷 복사본이 대상 볼륨으로 전송됩니다.

* 관련 정보 *

xref:reference_protection_window.adoc[보호 윈도우]
