---
permalink: online-help-96-97/task_creating_kerberos_realm_configurations.html 
sidebar: sidebar 
keywords: create, kerberos, realm, configuration, storage, virtual, machine, svm, online, help 
summary: '클라이언트 액세스에 Kerberos 인증을 사용하려면 기존 Kerberos 영역을 사용하도록 SVM(스토리지 가상 시스템)을 구성해야 합니다. System Manager를 사용하여 Kerberos 영역 구성을 생성할 수 있습니다. 이 구성을 사용하면 SVM에서 NFS에 Kerberos 보안 서비스를 사용할 수 있습니다.' 
---
= Kerberos 영역 구성을 만듭니다
:icons: font
:imagesdir: ../media/


[role="lead"]
클라이언트 액세스에 Kerberos 인증을 사용하려면 기존 Kerberos 영역을 사용하도록 SVM(스토리지 가상 시스템)을 구성해야 합니다. System Manager를 사용하여 Kerberos 영역 구성을 생성할 수 있습니다. 이 구성을 사용하면 SVM에서 NFS에 Kerberos 보안 서비스를 사용할 수 있습니다.

.시작하기 전에
* CIFS 공유를 사용하는 경우 CIFS 라이센스를 설치해야 하며 LDAP 서버를 사용하는 경우 NFS 라이센스를 설치해야 합니다.
* DES MD5 암호화 기능이 있는 Active Directory(Windows 2003 또는 Windows 2008)를 사용할 수 있어야 합니다.
* NTP를 구성하여 표준 시간대를 설정하고 클러스터 전체에서 시간을 동기화해야 합니다.
+
이렇게 하면 인증 오류가 방지되고 로그 파일의 타임스탬프가 클러스터 전체에서 일관되도록 할 수 있습니다.



Kerberos 영역을 만드는 동안 Kerberos 영역 만들기 마법사에서 다음 속성을 설정해야 합니다.

* Kerberos 영역
* KDC IP 주소 및 포트 번호입니다
+
기본 포트 번호는 88입니다.

* Kerberos KDC(키 배포 센터) 공급업체
* KDC 공급업체가 Microsoft가 아닌 경우 관리 서버 IP 주소입니다
* 암호 서버 IP 주소입니다
* KDC 공급업체가 Microsoft인 경우 Active Directory 서버 이름 및 IP 주소


.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 서비스 * 창에서 * Kerberos 영역 * 을 클릭합니다.
. Kerberos Realm* 창에서 * 생성 * 을 클릭합니다.
. 마법사의 지시에 따라 정보를 입력하거나 선택합니다.
. 세부 정보를 확인한 다음 * 마침 * 을 클릭하여 마법사를 완료합니다.


* 관련 정보 *

xref:task_setting_time_zone_for_cluster.adoc[클러스터의 시간대 설정]

link:https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["NetApp 기술 보고서 4067: NetApp ONTAP의 NFS"^]

link:https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf["NetApp 기술 보고서 4616: ONTAP에서 Microsoft Active Directory와 NFS Kerberos"^]

link:https://www.netapp.com/pdf.html?item=/media/19423-tr-4835.pdf["NetApp 기술 보고서 4835: ONTAP에서 LDAP를 구성하는 방법"^]
