---
permalink: online-help-96-97/task_configuring_administration_details_svm.html 
sidebar: sidebar 
keywords: storage, virtual, machine, configure, administration, details, svm, online, help, system, manager 
summary: 'System Manager를 사용하면 스토리지 가상 시스템(SVM)의 관리 세부 정보를 빠르게 구성할 수 있습니다. 선택적으로 SVM 관리자에게 SVM 관리 권한을 위임할 수 있습니다.' 
---
= SVM의 관리 세부 정보를 구성합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager를 사용하면 SVM(스토리지 가상 시스템)의 관리 세부 정보를 빠르게 구성할 수 있습니다. 선택적으로 SVM 관리자에게 SVM 관리 권한을 위임할 수 있습니다.

SVM 관리자는 System Manager를 사용하여 위임된 SVM을 관리할 수 없습니다. CLI(Command-Line Interface)를 사용해서만 SVM을 관리할 수 있습니다.

.단계
. 구성 * > * 클러스터 * > * 구성 업데이트 * 를 클릭합니다.
. SVM * 탭에서 노드를 선택한 다음 * 관리 세부 정보 구성 * 을 클릭합니다.
. 관리자 세부 정보 * 섹션에서 'vsadmin' 사용자 계정의 암호를 설정합니다.
. SVM 관리를 위한 전용 LIF를 원하는 경우 * SVM 관리를 위한 LIF 생성 * 을 선택하고 네트워크 세부 정보를 지정합니다.
+
SAN 프로토콜에는 데이터 및 관리 프로토콜이 동일한 LIF를 공유할 수 없는 전용 SVM 관리 LIF가 필요합니다. SVM 관리 LIF는 데이터 포트에만 생성할 수 있습니다.

. 네트워크 세부 정보를 지정합니다.
+
|===
| 원하는 작업 | 그러면... 


 a| 
서브넷을 사용하여 IP 주소를 지정합니다
 a| 
.. 서브넷 사용 * 을 선택합니다.
.. 세부 정보 추가 대화 상자에서 IP 주소를 할당해야 하는 서브넷을 선택합니다.
+
인터클러스터 LIF의 경우 선택한 IPspace와 연결된 서브넷만 표시됩니다.

.. 인터페이스에 특정 IP 주소를 할당하려면 * 특정 IP 주소 사용 * 을 선택한 다음 IP 주소를 입력합니다.
+
지정한 IP 주소가 서브넷 범위에 없는 경우 서브넷에 추가됩니다.

.. 확인 * 을 클릭합니다.




 a| 
서브넷을 사용하지 않고 수동으로 IP 주소를 지정합니다
 a| 
.. 서브넷 없이 * 를 선택합니다.
.. 세부 정보 추가 대화 상자에서 다음 단계를 수행합니다.
+
... IP 주소와 네트워크 마스크 또는 접두사를 지정합니다.
... 선택 사항: 게이트웨이를 지정합니다.
+
대상 필드는 IP 주소 패밀리를 기준으로 기본값으로 채워집니다.

... 기본값을 사용하지 않으려면 새 목적지 값을 지정하십시오. 라우트가 존재하지 않으면 게이트웨이와 목적지를 기반으로 새 루트가 자동으로 생성됩니다.


.. 확인 * 을 클릭합니다.


|===
. 데이터 LIF를 생성할 포트를 지정합니다.
+
.. 찾아보기 * 를 클릭합니다.
.. 네트워크 포트 또는 어댑터 선택 * 대화 상자에서 포트를 선택한 다음 * 확인 * 을 클릭합니다.



