---
permalink: online-help-96-97/task_creating_mirror_relationship_from_destination_svm.html 
sidebar: sidebar 
keywords: create, mirror, relationship, destination, svm, online, help, system, manager 
summary: 'ONTAP System Manager를 사용하여 대상 SVM(스토리지 가상 머신)에서 미러링 관계를 생성하고 정책 및 일정을 미러 관계에 할당할 수 있습니다. 미러 복제본을 사용하면 소스 볼륨의 데이터가 손상되거나 손실된 경우 데이터를 빠르게 사용할 수 있습니다.' 
---
= System Manager - ONTAP 9.7 이하를 사용하여 대상 SVM에서 미러링 관계를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 타겟 SVM(스토리지 가상 머신)에서 미러 관계를 생성하고 정책과 일정을 미러 관계에 할당할 수 있습니다. 미러 복제본을 사용하면 소스 볼륨의 데이터가 손상되거나 손실된 경우 데이터를 빠르게 사용할 수 있습니다.

.시작하기 전에
* 소스 클러스터는 ONTAP 8.2.2 이상을 실행해야 합니다.
* 소스 클러스터와 대상 클러스터에서 SnapMirror 라이센스가 활성화되어야 합니다.
+
[NOTE]
====
일부 플랫폼의 경우 대상 클러스터에 SnapMirror 라이센스 및 DPO(데이터 보호 최적화) 라이센스가 활성화되어 있는 경우 소스 클러스터에 SnapMirror 라이센스가 활성화되어 있지 않아도 됩니다.

====
* 볼륨을 미러링하는 동안 SnapLock 볼륨을 소스로 선택하면 SnapMirror 라이센스와 SnapLock 라이센스가 대상 클러스터에 설치되어 있어야 합니다.
* 소스 클러스터와 대상 클러스터는 정상 피어 관계에 있어야 합니다.
* 대상 SVM에 사용 가능한 공간이 있어야 합니다.
* 읽기/쓰기(RW) 유형의 소스 볼륨이 있어야 합니다.
* FlexVol 볼륨은 온라인이어야 하며 읽기/쓰기 유형이어야 합니다.
* SnapLock 집계 유형은 같은 유형이어야 합니다.
* ONTAP 9.2 이하 버전을 실행하는 클러스터에서 SAML(Security Assertion Markup Language) 인증이 활성화된 원격 클러스터로 연결하는 경우 원격 클러스터에서 암호 기반 인증을 활성화해야 합니다.


.이 작업에 대해
* System Manager는 계단식 관계를 지원하지 않습니다.
+
예를 들어, 관계의 대상 볼륨은 다른 관계의 소스 볼륨이 될 수 없습니다.

* MetroCluster 구성에서 동기화 소스 SVM과 동기화 대상 SVM 간에 미러 관계를 생성할 수 없습니다.
* MetroCluster 구성에서 동기화 소스 SVM 간에 미러 관계를 생성할 수 있습니다.
* 동기화 소스 SVM의 볼륨에서 데이터 지원 SVM의 볼륨으로 미러 관계를 생성할 수 있습니다.
* 데이터 지원 SVM의 볼륨에서 동기화 소스 SVM의 데이터 보호(DP) 볼륨으로 미러 관계를 생성할 수 있습니다.
* 같은 유형의 SnapLock 볼륨에만 미러 관계를 생성할 수 있습니다.
+
예를 들어 소스 볼륨이 SnapLock 엔터프라이즈 볼륨인 경우 대상 볼륨도 SnapLock 엔터프라이즈 볼륨이어야 합니다. 대상 SVM에 사용 가능한 SnapLock 유형의 애그리게이트가 있는지 확인해야 합니다.

* 미러 관계를 위해 생성된 타겟 볼륨이 씬 프로비저닝되지 않습니다.
* 한 번에 최대 25개의 볼륨을 보호할 수 있습니다.
* 타겟 클러스터에서 소스 클러스터가 실행 중인 ONTAP 버전보다 이전 버전의 ONTAP를 실행 중인 경우 SnapLock 볼륨 간에 미러 관계를 생성할 수 없습니다.


.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 볼륨 관계 * 창에서 * 생성 * 을 클릭합니다.
. SVM * 찾아보기 대화 상자에서 타겟 볼륨의 SVM을 선택합니다.
. [보호 관계 작성] * 대화 상자의 [관계 유형 *] 드롭다운 목록에서 [미러 *]를 선택합니다.
. 클러스터, SVM 및 소스 볼륨을 지정합니다.
+
지정된 클러스터에서 ONTAP 9.3 이전 버전의 ONTAP 소프트웨어를 실행 중인 경우 피어링된 SVM만 나열됩니다. 지정된 클러스터에서 ONTAP 9.3 이상이 실행 중인 경우 피어링된 SVM 및 허용된 SVM이 나열됩니다.

. FlexVol 볼륨의 경우 볼륨 이름 접미사를 지정합니다.
+
대상 볼륨 이름을 생성하기 위해 소스 볼륨 이름에 볼륨 이름 접미사가 추가됩니다.

. 찾아보기 * 를 클릭한 다음 미러 정책을 변경합니다.
. 기존 일정 목록에서 관계의 일정을 선택합니다.
. 미러 관계를 초기화하려면 * 관계 초기화 * 를 선택합니다.
. FabricPool 지원 애그리게이트를 사용하도록 설정한 다음 적절한 계층화 정책을 선택합니다.
. Create * 를 클릭합니다.


대상 볼륨을 만들도록 선택한 경우, 소스 볼륨의 언어 특성과 일치하도록 설정된 언어 속성을 사용하여 _DP_ 유형의 대상 볼륨이 생성됩니다.

소스 볼륨과 타겟 볼륨 사이에 미러 관계가 생성됩니다. 관계를 초기화하기로 선택한 경우 기본 스냅샷 복사본이 대상 볼륨으로 전송됩니다.

* 관련 정보 *

xref:reference_protection_window.adoc[보호 윈도우]
