---
permalink: online-help-96-97/task_changing_peering_encryption_status.html 
sidebar: sidebar 
keywords: change, peer, encryption, status, system, manager, cluster, online, help 
summary: System Manager를 사용하여 선택한 클러스터의 피어링 암호화 상태를 변경할 수 있습니다. 
---
= 피어링 암호화 상태 변경
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager를 사용하여 선택한 클러스터의 피어링 암호화 상태를 변경할 수 있습니다.

암호화 상태는 활성화 또는 비활성화할 수 있습니다. 암호화 변경 * 을 선택하여 상태를 사용 가능에서 사용 안 함으로 또는 사용 안 함 에서 사용으로 변경할 수 있습니다.

.단계
. 구성 * > * 클러스터 피어 * 를 클릭합니다.
. 피어링된 클러스터를 선택하고 * Edit * 를 클릭합니다
+
드롭다운 메뉴가 표시됩니다.

. 암호화 변경 * 을 클릭합니다.
+
암호화 상태가 "해당 없음"인 경우 이 작업을 사용할 수 없습니다.

+
암호화 변경 대화 상자가 표시됩니다. 토글 단추는 현재 암호화 상태를 나타냅니다.

. 토글 버튼을 밀어 피어링 암호화 상태를 변경하고 계속 진행합니다.
+
** 현재 암호화 상태가 ""없음""인 경우 전환 버튼을 밀어 상태를 ""TLS_PSK""로 변경하여 암호화를 활성화할 수 있습니다.
** 현재 암호화 상태가 "'TLS_PSK''인 경우 전환 버튼을 밀어 상태를 "'없음''으로 변경하여 암호화를 비활성화할 수 있습니다.


. 피어링 암호화를 활성화 또는 비활성화한 후, 새 암호를 생성하여 피어링된 클러스터에 제공하거나 피어링된 클러스터에서 이미 생성된 기존 암호를 적용할 수 있습니다.
+
[NOTE]
====
로컬 사이트에서 사용되는 암호가 원격 사이트에서 사용되는 암호와 일치하지 않으면 클러스터 피어링 관계가 제대로 작동하지 않습니다.

====
+
다음 중 하나를 선택합니다.

+
** * 암호문 생성 *: 단계로 진행합니다 <<STEP_1ABAF15926174E709CA59192E200ABE3,STEP_1ABAF15926174E709CA59192E200ABE3>>.
** * 이미 패스프레이즈가 있습니다 *: 단계로 이동합니다 <<STEP_2EFD822431974811AD2260C3F31DC977,STEP_2EFD822431974811AD2260C3F31DC977>>.


. 암호 생성 * 을 선택한 경우 필요한 필드를 입력합니다.
+
** * IPspace *: 드롭다운 메뉴에서 IPspace를 선택합니다.
** * Passphrase Validity *: 드롭다운 메뉴에서 패스프레이즈를 유효하게 할 기간을 선택합니다.
** * SVM 권한 *: 다음 중 하나를 선택합니다.
+
*** 모든 SVM * 이 클러스터에 액세스할 수 있음을 나타냅니다.
*** * 클러스터에 액세스할 수 있는 특정 SVM을 나타내기 위해 SVM * 이 선택되었습니다. 지정할 필드에서 SVM 이름을 강조 표시합니다.




. 원격 클러스터의 유효 클러스터 버전이 ONTAP 9.6 이전인 경우 확인란을 선택합니다. 그렇지 않으면 암호가 생성되지 않습니다.
. 적용 * 을 클릭합니다.
+
패스프레이즈는 관계에 대해 생성되고 표시됩니다. 암호문을 복사하거나 이메일로 보낼 수 있습니다.

+
로컬 클러스터의 인증 상태는 원격 클러스터에서 암호를 제공할 때까지 선택한 암호 유효 기간 동안 "ok_and_Offer"로 표시됩니다.

. 원격 클러스터에서 새 암호를 이미 생성한 경우 다음 하위 단계를 수행하십시오.
+
.. 암호 * 가 이미 있습니다 * 를 클릭합니다.
.. 원격 클러스터에서 생성된 것과 동일한 암호를 * Passphrase * 필드에 입력합니다.
.. 적용 * 을 클릭합니다.



