---
permalink: online-help-96-97/task_editing_vault_relationships.html 
sidebar: sidebar 
keywords: edit, vault, relationships, system, manager, online, help, cluster, schedule 
summary: System Manager를 사용하여 클러스터에서 기존 정책 또는 일정을 선택하거나 새 정책 또는 일정을 만들어 볼트 관계를 편집할 수 있습니다. 그러나 기존 정책 또는 스케줄의 매개 변수는 편집할 수 없습니다. 
---
= 볼트 관계 편집
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager를 사용하여 클러스터에서 기존 정책 또는 일정을 선택하거나 새 정책 또는 일정을 만들어 볼트 관계를 편집할 수 있습니다. 그러나 기존 정책 또는 스케줄의 매개 변수는 편집할 수 없습니다.

소스 및 대상 클러스터는 정상 피어 관계에 있어야 합니다.

.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 정책 또는 일정을 수정하려는 볼트 관계를 선택하고 * 편집 * 을 클릭합니다.
. [관계 편집] * 대화 상자에서 적절한 작업을 선택합니다.
+
|===
| 원하는 작업 | 다음을 수행합니다. 


 a| 
기존 정책을 선택합니다
 a| 
찾아보기 * 를 클릭한 다음 기존 정책을 선택합니다. 소스 볼륨에 연결된 스냅샷 정책과 일치하는 최대 레이블 수를 갖는 정책을 선택할 수 있습니다.



 a| 
새 정책을 생성합니다
 a| 
.. Create Policy * 를 클릭합니다.
.. 정책의 이름을 지정합니다.
.. 예약된 전송의 우선 순위를 설정합니다.
+
낮음 은 전송 우선 순위가 가장 낮으며 일반적으로 일반 우선 순위 전송 후에 예약됨을 나타냅니다. 기본적으로 우선 순위는 보통으로 설정됩니다.

.. 전송 중인 데이터를 압축하려면 * 네트워크 압축 사용 * 확인란을 선택합니다.
.. 볼트 정책에 대한 SnapMirror 레이블 및 대상 보존 수를 지정합니다.
+
새 SnapMirror 레이블을 사용하려면 소스 볼륨에 동일한 레이블이 있는 스냅샷 복사본이 생성되었는지 확인해야 합니다.

.. Create * 를 클릭합니다.


|===
. 관계의 일정을 지정합니다.
+
|===
| 만약... | 다음을 수행합니다. 


 a| 
기존 일정을 할당하려고 합니다
 a| 
목록에서 기존 일정을 선택합니다.



 a| 
새 스케줄을 생성하려고 합니다
 a| 
.. Create Schedule * 을 클릭합니다.
.. 스케줄의 이름을 지정합니다.
.. 다음 옵션 중 하나를 선택합니다.
+
*** * 기본 *
+
이 옵션을 선택하면 요일, 시간 및 전송 간격만 지정할 수 있습니다.

*** * 고급 *
+
이 옵션을 선택하여 cron 스타일 일정을 지정할 수 있습니다.



.. Create * 를 클릭합니다.




 a| 
일정을 지정하지 않으려는 경우
 a| 
없음 * 을 선택합니다.

|===
. 확인 * 을 클릭합니다.


* 관련 정보 *

xref:reference_protection_window.adoc[보호 윈도우]
