---
permalink: online-help-96-97/task_setting_up_network_when_ip_address_range_is_disabled.html 
sidebar: sidebar 
keywords: set, up, network, ip, address, disabled, network, online, help 
summary: IP 주소 범위를 사용하지 않도록 설정하고 클러스터 관리, 노드 관리 및 서비스 공급자 네트워크에 대한 개별 IP 주소를 입력하여 네트워크를 설정할 수 있습니다. 
---
= IP 주소 범위가 비활성화된 경우 네트워크 설정
:icons: font
:imagesdir: ../media/


[role="lead"]
IP 주소 범위를 사용하지 않도록 설정하고 클러스터 관리, 노드 관리 및 서비스 공급자 네트워크에 대한 개별 IP 주소를 입력하여 네트워크를 설정할 수 있습니다.

네트워크 페이지에서 * IP 주소 범위 * 가 비활성화되어 있으면 클러스터 관리, 노드 관리 및 서비스 프로세서 네트워크의 개별 IP 주소를 입력합니다.

.단계
. Cluster Management IP Address * 필드에 클러스터 관리 IP 주소를 입력합니다.
. 클러스터 관리에 대한 넷마스크 세부 정보를 입력합니다.
. 클러스터 관리를 위한 게이트웨이 세부 정보를 입력합니다.
. Port * 필드에서 클러스터 관리용 포트를 선택합니다.
. 노드를 관리할 넷마스크 및 게이트웨이 세부 정보를 제공하려면 클러스터 관리 * 의 넷마스크 및 게이트웨이 구성 * 보존 확인란의 선택을 취소한 다음 넷마스크 및 게이트웨이 세부 정보를 입력합니다.
. Node Management * 필드에 노드 관리 IP 주소를 입력합니다.
. 노드 관리의 * 포트 * 필드가 * e0M * 으로 채워지지 않은 경우 포트 세부 정보를 입력합니다.
+
[NOTE]
====
기본적으로 포트 필드에는 e0M이 표시됩니다.

====
. 서비스 프로세서 관리 넷마스크 및 게이트웨이 세부 정보를 입력합니다.
. 서비스 프로세서 관리 * 필드에 서비스 프로세서 IP 관리 주소를 입력합니다.
. DNS 세부 정보 * 필드를 활성화한 경우 DNS 서버 세부 정보를 입력합니다.
. NTP 세부 정보 * 필드를 활성화한 경우 NTP 서버 세부 정보를 입력합니다.
+
[NOTE]
====
대체 NTP 서버 세부 정보를 제공하는 것은 선택 사항입니다.

====
. 제출 * 을 클릭합니다.




== 다음 단계

클러스터 설정을 계속하려면 지원 페이지에 이벤트 알림을 입력하십시오.

* 관련 정보 *

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/What_is_a_Service_Processor_and_how_do_I_use_it%3F["서비스 프로세서란 무엇이며 어떻게 사용합니까?"]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_configure_and_troubleshoot_NTP_on_clustered_Data_ONTAP_8.2_and_later_using_CLI["CLI를 사용하여 clustered Data ONTAP 8.2 이상에서 NTP를 구성 및 문제 해결하는 방법"]

https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 문서 센터"]

xref:reference_network_window.adoc[네트워크 창]

xref:reference_configuration_updates_window.adoc[Configuration Updates(구성 업데이트) 창]

xref:reference_date_time_window.adoc[날짜 및 시간 창]

xref:reference_service_processors_window.adoc[서비스 프로세서 창]
