---
permalink: nfs-config-esxi/index.html 
sidebar: sidebar 
keywords: nfs, access, esxi, host, datastores, ontap, volume, configuration, overview, vsc 
summary: 이 내용은 ONTAP 볼륨을 사용하여 ESXi 호스트에 대한 NFS 액세스를 데이터 저장소에 빠르게 설정하는 방법을 설명합니다. 
---
= VSC 개요를 사용한 ESXi용 NFS 구성
:icons: font
:imagesdir: ../media/


[role="lead"]
이 내용은 ONTAP 볼륨을 사용하여 ESXi 호스트에 대한 NFS 액세스를 데이터 저장소에 빠르게 설정하는 방법을 설명합니다.

다음과 같은 방법으로 ESXi 호스트에 대한 NFS 액세스를 볼륨에 구성하려면 이 콘텐츠를 사용해야 합니다.

* ONTAP 9를 실행하는 클러스터로 작업하고 있습니다.
* 사용 가능한 모든 옵션을 탐색하는 것이 아니라 모범 사례를 사용하려고 합니다.
* 많은 개념적 배경을 읽고 싶지 않습니다.
* 를 사용하여 데이터 저장소를 프로비저닝하고 볼륨을 생성하려고 합니다.
* ONTAP 9.7 이상을 위한 ONTAP 시스템 관리자 UI가 아니라 ONTAP 9.7 이전 릴리즈용 _Classic_System Manager UI를 사용하려고 합니다.
+
https://docs.netapp.com/us-en/ontap/["ONTAP 시스템 관리자 설명서"^]

* 데이터 네트워크는 기본 IPspace, 기본 브로드캐스트 도메인 및 기본 페일오버 그룹을 사용합니다.
+
데이터 네트워크가 평평하게 되어 있는 경우, 이 기본 오브젝트는 링크 장애 시 LIF가 올바르게 페일오버되도록 규정합니다. 기본 개체를 사용하지 않는 경우 을 참조해야 합니다 https://docs.netapp.com/us-en/ontap/networking/index.html["네트워크 관리"] LIF 경로 페일오버를 구성하는 방법에 대한 자세한 내용은 를 참조하십시오.

* VMware VAAI용 플러그인을 사용하려는 경우
+
VAAI(VMware vStorage APIs for Array Integration)를 사용하면 복제 오프로드 및 공간 예약을 수행할 수 있습니다. VMware VAAI용 플러그인은 ESXi 호스트를 통과할 필요가 없으므로 ONTAP에서 공간 및 시간 효율성이 뛰어난 클론 생성을 활용할 수 있으므로 이를 사용하여 호스트 성능을 향상시킵니다.

+
데이터 저장소 용량 할당에 VMware VAAI를 사용하는 것이 Best Practice입니다.

* NFS 액세스는 VMware VAAI에서 사용할 수 있도록 NFSv3 및 NFSv4를 통해 이루어집니다.


이 내용이 상황에 적합하지 않은 경우 다음 문서를 참조하십시오.

* https://docs.netapp.com/us-en/ontap/nfs-admin/index.html["NFS 관리"^]
* http://www.netapp.com/us/media/tr-4067.pdf["NetApp 기술 보고서 4067: NFS 모범 사례 및 구현"^]
* https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["NetApp 기술 보고서 4668: 이름 서비스 모범 사례"^]
* http://www.netapp.com/us/media/tr-4597.pdf["NetApp 기술 보고서 4597: ONTAP이 포함된 VMware vSphere"^]

