---
permalink: nfs-config-esxi/reference_where_to_find_additional_information.html 
sidebar: sidebar 
keywords: successful, test, nfs, client, access, configuration, san, protocol, complete, protect, root, volume, comprehensive, technical, report, goal, where to find additional information 
summary: NFS 클라이언트 액세스를 성공적으로 테스트한 후 추가 NFS 구성을 수행하거나 SAN 액세스를 추가할 수 있습니다. 프로토콜 액세스가 완료되면 의 루트 볼륨을 보호해야 합니다. 이러한 목표를 달성하는 데 도움이 되는 포괄적인 컨텐츠 및 기술 보고서가 있습니다. 
---
= 추가 정보를 찾을 수 있는 위치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS 클라이언트 액세스를 성공적으로 테스트한 후 추가 NFS 구성을 수행하거나 SAN 액세스를 추가할 수 있습니다. 프로토콜 액세스가 완료되면 의 루트 볼륨을 보호해야 합니다. 이러한 목표를 달성하는 데 도움이 되는 포괄적인 컨텐츠 및 기술 보고서가 있습니다.



== NFS 구성

다음 콘텐츠 및 기술 보고서를 사용하여 NFS 액세스를 추가로 구성할 수 있습니다.

* https://docs.netapp.com/us-en/ontap/nfs-config/index.html["NFS 구성"^]
+
CLI 명령을 사용하여 새 볼륨 또는 qtree에 포함된 파일에 대한 고급 NFS 클라이언트 액세스를 구성하는 방법에 대한 설명은 에 나와 있습니다.

* https://docs.netapp.com/us-en/ontap/nfs-admin/index.html["NFS 관리"^]
+
인증, 권한 부여 및 보안을 포함하여 NFS 프로토콜을 사용하여 파일 액세스를 관리하는 방법에 대한 설명은 에 나와 있습니다.

* http://www.netapp.com/us/media/tr-4597.pdf["NetApp 기술 보고서 4597: ONTAP이 포함된 VMware vSphere"^]
+
에서는 ONTAP 및 VMware vSphere 서버 가상화 환경을 사용할 때 따라야 하는 Best Practice를 설명합니다.

* https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["NetApp 기술 보고서 4668: 이름 서비스 모범 사례"^]
+
인증을 위해 LDAP, NIS, DNS 및 로컬 사용자 및 그룹 파일을 구성할 때 고려해야 할 사항과 제한 사항, 권장 사항 및 사항에 대한 포괄적인 목록을 제공합니다.

* http://www.netapp.com/us/media/tr-4067.pdf["NetApp 기술 보고서 4067: NFS 모범 사례 및 구현"^]
+
NFSv4를 중심으로 ONTAP에 대해 간략하게 설명합니다.





== 루트 볼륨 보호

SVM에서 프로토콜을 구성한 후에는 루트 볼륨이 보호되는지 확인해야 합니다.

* https://docs.netapp.com/us-en/ontap/data-protection/index.html["데이터 보호"^]
+
로드 공유 미러를 생성하여 NAS 지원 SVM에 대한 NetApp의 모범 사례인 루트 볼륨을 보호하는 방법에 대해 설명합니다. 또한, 로드 공유 미러에서 SVM 루트 볼륨을 프로모션하여 볼륨 장애 또는 손실로부터 빠르게 복구하는 방법을 설명합니다.


