---
permalink: fc-config-esxi/index.html 
sidebar: sidebar 
keywords: fc, service, storage, virtual, machine, svm, provision, lun, fc, hba, esx, host, computer, 
summary: 'ONTAP System Manager의 기존 인터페이스(ONTAP 9.7 이하)를 사용하면 SVM(스토리지 가상 머신)에서 FC 서비스를 빠르게 설정하고, LUN을 프로비저닝하고, ESX 호스트 컴퓨터의 FC HBA를 사용하여 LUN을 데이터 저장소로 사용할 수 있습니다.' 
---
= VSC 개요를 사용하여 ESXi용 FC 구성
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager의 기존 인터페이스(ONTAP 9.7 이하)를 사용하면 SVM(스토리지 가상 머신)에서 FC 서비스를 빠르게 설정하고, LUN을 프로비저닝하고, ESX 호스트 컴퓨터의 FC HBA를 사용하여 LUN을 데이터 저장소로 사용할 수 있습니다.

다음 경우에 이 절차를 사용합니다.

* 지원되는 버전의 VMware vSphere용 Virtual Storage Console을 사용하여 ESX 호스트에 대한 스토리지 설정을 구성하고 데이터 저장소를 프로비저닝하고 있습니다.
* 네트워크는 IPv4 주소 지정을 사용합니다.
* ESXi 5.x 및 기존 FC 스위치에서 기존 FC HBA를 사용하고 있습니다.
+
이 절차는 FCoE에 적용되지 않습니다.

* 클러스터의 각 노드에서 사용 가능한 FC 타겟 포트가 2개 이상 있습니다.
+
온보드 FC 및 UTA2("CNA") 포트뿐만 아니라 일부 어댑터를 구성할 수 있습니다. 이러한 포트 구성은 ONTAP CLI에서 수행되며 이 절차에서 다루지 않습니다.

* FC SAN 부팅을 구성하지 않습니다.
* 호스트에서 데이터 저장소를 생성하는 중입니다.
+
이 절차에서는 RDM(Raw Device Mapping) 디스크 또는 NPIV(N-Port ID Virtualization)를 사용하여 FC를 VM에 직접 제공하는 방법에 대해 다루지 않습니다.





== ONTAP에서 이 작업을 수행하는 다른 방법

[cols="2"]
|===
| 에서 이러한 작업을 수행하려면... | 이 콘텐츠 보기... 


| 재설계된 System Manager(ONTAP 9.7 이상에서 사용 가능) | link:https://docs.netapp.com/us-en/ontap/task_san_provision_vmware.html["VMware 데이터 저장소에 SAN 스토리지 용량 할당"^] 


| ONTAP CLI(Command Line Interface) | link:https://docs.netapp.com/us-en/ontap/san-admin/lun-setup-workflow-concept.html["CLI를 사용한 LUN 설정 워크플로우"^] 
|===


== 추가 리소스

이러한 가정이 현재 상황에 맞지 않는 경우 다음 리소스를 참조하십시오.

* https://docs.netapp.com/us-en/ontap/san-admin/index.html["ONTAP 9 SAN 관리"^]
* https://docs.netapp.com/us-en/ontap/san-config/index.html["ONTAP 9 SAN 구성"^]
* https://docs.netapp.com/vapp-96/topic/com.netapp.doc.vsc-iag/home.html["어플라이언스 관리"^]
* _VMware vSphere Storage_ - ESXi 5 버전용(에서 제공 link:http://www.vmware.com["VMware"^])

